// Code generated by ent, DO NOT EDIT.

package upstreambalancesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upstreambalancesnapshot type in the database.
	Label = "upstream_balance_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUpstreamType holds the string denoting the upstream_type field in the database.
	FieldUpstreamType = "upstream_type"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldSnapshotAt holds the string denoting the snapshot_at field in the database.
	FieldSnapshotAt = "snapshot_at"
	// Table holds the table name of the upstreambalancesnapshot in the database.
	Table = "upstream_balance_snapshots"
)

// Columns holds all SQL columns for upstreambalancesnapshot fields.
var Columns = []string{
	FieldID,
	FieldUpstreamType,
	FieldAccountID,
	FieldBalance,
	FieldCurrency,
	FieldSnapshotAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UpstreamTypeValidator is a validator for the "upstream_type" field. It is called by the builders before save.
	UpstreamTypeValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultSnapshotAt holds the default value on creation for the "snapshot_at" field.
	DefaultSnapshotAt func() time.Time
)

// OrderOption defines the ordering options for the UpstreamBalanceSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUpstreamType orders the results by the upstream_type field.
func ByUpstreamType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamType, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// BySnapshotAt orders the results by the snapshot_at field.
func BySnapshotAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotAt, opts...).ToFunc()
}
