// Code generated by ent, DO NOT EDIT.

package upstreambalancesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLTE(FieldID, id))
}

// UpstreamType applies equality check predicate on the "upstream_type" field. It's identical to UpstreamTypeEQ.
func UpstreamType(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldUpstreamType, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldBalance, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldCurrency, v))
}

// SnapshotAt applies equality check predicate on the "snapshot_at" field. It's identical to SnapshotAtEQ.
func SnapshotAt(v time.Time) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldSnapshotAt, v))
}

// UpstreamTypeEQ applies the EQ predicate on the "upstream_type" field.
func UpstreamTypeEQ(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldUpstreamType, v))
}

// UpstreamTypeNEQ applies the NEQ predicate on the "upstream_type" field.
func UpstreamTypeNEQ(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNEQ(FieldUpstreamType, v))
}

// UpstreamTypeIn applies the In predicate on the "upstream_type" field.
func UpstreamTypeIn(vs ...string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldIn(FieldUpstreamType, vs...))
}

// UpstreamTypeNotIn applies the NotIn predicate on the "upstream_type" field.
func UpstreamTypeNotIn(vs ...string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNotIn(FieldUpstreamType, vs...))
}

// UpstreamTypeGT applies the GT predicate on the "upstream_type" field.
func UpstreamTypeGT(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGT(FieldUpstreamType, v))
}

// UpstreamTypeGTE applies the GTE predicate on the "upstream_type" field.
func UpstreamTypeGTE(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGTE(FieldUpstreamType, v))
}

// UpstreamTypeLT applies the LT predicate on the "upstream_type" field.
func UpstreamTypeLT(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLT(FieldUpstreamType, v))
}

// UpstreamTypeLTE applies the LTE predicate on the "upstream_type" field.
func UpstreamTypeLTE(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLTE(FieldUpstreamType, v))
}

// UpstreamTypeContains applies the Contains predicate on the "upstream_type" field.
func UpstreamTypeContains(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldContains(FieldUpstreamType, v))
}

// UpstreamTypeHasPrefix applies the HasPrefix predicate on the "upstream_type" field.
func UpstreamTypeHasPrefix(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldHasPrefix(FieldUpstreamType, v))
}

// UpstreamTypeHasSuffix applies the HasSuffix predicate on the "upstream_type" field.
func UpstreamTypeHasSuffix(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldHasSuffix(FieldUpstreamType, v))
}

// UpstreamTypeEqualFold applies the EqualFold predicate on the "upstream_type" field.
func UpstreamTypeEqualFold(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEqualFold(FieldUpstreamType, v))
}

// UpstreamTypeContainsFold applies the ContainsFold predicate on the "upstream_type" field.
func UpstreamTypeContainsFold(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldContainsFold(FieldUpstreamType, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLTE(FieldAccountID, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLTE(FieldBalance, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldContainsFold(FieldCurrency, v))
}

// SnapshotAtEQ applies the EQ predicate on the "snapshot_at" field.
func SnapshotAtEQ(v time.Time) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldEQ(FieldSnapshotAt, v))
}

// SnapshotAtNEQ applies the NEQ predicate on the "snapshot_at" field.
func SnapshotAtNEQ(v time.Time) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNEQ(FieldSnapshotAt, v))
}

// SnapshotAtIn applies the In predicate on the "snapshot_at" field.
func SnapshotAtIn(vs ...time.Time) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldIn(FieldSnapshotAt, vs...))
}

// SnapshotAtNotIn applies the NotIn predicate on the "snapshot_at" field.
func SnapshotAtNotIn(vs ...time.Time) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldNotIn(FieldSnapshotAt, vs...))
}

// SnapshotAtGT applies the GT predicate on the "snapshot_at" field.
func SnapshotAtGT(v time.Time) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGT(FieldSnapshotAt, v))
}

// SnapshotAtGTE applies the GTE predicate on the "snapshot_at" field.
func SnapshotAtGTE(v time.Time) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldGTE(FieldSnapshotAt, v))
}

// SnapshotAtLT applies the LT predicate on the "snapshot_at" field.
func SnapshotAtLT(v time.Time) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLT(FieldSnapshotAt, v))
}

// SnapshotAtLTE applies the LTE predicate on the "snapshot_at" field.
func SnapshotAtLTE(v time.Time) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.FieldLTE(FieldSnapshotAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamBalanceSnapshot) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamBalanceSnapshot) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamBalanceSnapshot) predicate.UpstreamBalanceSnapshot {
	return predicate.UpstreamBalanceSnapshot(sql.NotPredicates(p))
}
