<template>
  <AppLayout>
    <div class="space-y-5"><header class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-xl font-semibold text-gray-900 dark:text-white">教程高级设置</h1><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">管理教程路径、状态、排序和正文内容。</p></div><button class="btn btn-primary" @click="newTutorial">＋ 新建教程</button></header>
      <div class="grid min-h-[650px] gap-4 lg:grid-cols-[280px_minmax(0,1fr)]"><aside class="card overflow-auto p-3"><input v-model="search" class="input mb-3" placeholder="搜索教程" aria-label="搜索教程"><button v-for="item in filtered" :key="item.id" class="mb-1 block w-full rounded-lg border p-3 text-left" :class="selected?.id===item.id?'border-primary-300 bg-primary-50 dark:bg-primary-900/20':'border-transparent hover:bg-gray-50 dark:hover:bg-dark-700'" @click="select(item)"><span class="block truncate text-sm font-medium text-gray-900 dark:text-white"><span class="mr-1 inline-block h-2 w-2 rounded-full" :class="item.status==='published'?'bg-emerald-500':'bg-slate-400'"></span>{{ item.title }}</span><span class="mt-1 block truncate text-xs text-gray-400">/tutorial/{{ item.slug }} · {{ statusLabel(item.status) }}</span></button></aside>
        <main class="card flex min-w-0 flex-col overflow-hidden"><form class="flex min-h-0 flex-1 flex-col" @submit.prevent="save"><div class="grid gap-4 border-b border-gray-100 p-5 dark:border-dark-700 md:grid-cols-2"><label class="input-label">标题<input v-model.trim="form.title" class="input mt-1" maxlength="160" required></label><label class="input-label">分享路径<div class="mt-1 flex items-center rounded-lg border border-gray-200 dark:border-dark-600"><span class="pl-3 text-sm text-gray-400">/tutorial/</span><input v-model.trim="form.slug" class="min-w-0 flex-1 bg-transparent px-1 py-2 text-sm outline-none" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required></div></label><label class="input-label">分类<select v-model="form.category" class="input mt-1"><option value="getting-started">开始使用</option><option value="clients">客户端接入</option><option value="billing">充值与订阅</option><option value="troubleshooting">问题排查</option></select></label><label class="input-label">状态<select v-model="form.status" class="input mt-1"><option value="draft">草稿</option><option value="published">已发布</option><option value="offline">已下线</option></select></label><label class="input-label md:col-span-2">摘要<textarea v-model.trim="form.summary" class="input mt-1 min-h-20" maxlength="400"></textarea></label></div><div class="border-b border-gray-100 p-4 dark:border-dark-700"><div class="flex flex-wrap gap-2"><button v-for="tool in tools" :key="tool.label" type="button" class="btn btn-secondary btn-sm" @click="insert(tool.before,tool.after)">{{ tool.label }}</button><button type="button" class="btn btn-secondary btn-sm" @click="preview=!preview">{{ preview?'编辑':'预览' }}</button></div></div><textarea v-if="!preview" v-model="form.content_markdown" class="min-h-[24rem] flex-1 resize-none border-0 bg-transparent p-5 font-mono text-sm leading-7 outline-none" spellcheck="false" required></textarea><div v-else class="tutorial-preview flex-1 p-5" v-html="previewHtml"></div><footer class="flex flex-wrap items-center justify-between gap-3 border-t border-gray-100 bg-gray-50 px-5 py-3 dark:border-dark-700 dark:bg-dark-900"><span class="text-xs text-gray-400">{{ saving?'保存中…':selected?'编辑中':'新教程' }}</span><div class="flex gap-2"><button v-if="selected" type="button" class="btn btn-danger" @click="remove">删除</button><button type="submit" class="btn btn-primary" :disabled="saving">保存更改</button></div></footer></form></main>
      </div></div>
  </AppLayout>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import DOMPurify from 'dompurify';import { marked } from 'marked';import AppLayout from '@/components/layout/AppLayout.vue';import { useAppStore } from '@/stores';import { createTutorial, deleteTutorial, listAdminTutorials, setTutorialStatus, updateTutorial, type Tutorial } from '@/api/tutorial'
const appStore=useAppStore();const items=ref<Tutorial[]>([]);const selected=ref<Tutorial|null>(null);const search=ref('');const preview=ref(false);const saving=ref(false)
const form=reactive<{slug:string;title:string;summary:string;category:string;content_html:string;content_markdown:string;is_public:boolean;sort_order:number;status:Tutorial['status']}>({slug:'new-tutorial',title:'新教程',summary:'',category:'getting-started',content_html:'',content_markdown:'# 新教程\n\n在这里填写教程正文。',is_public:false,sort_order:100,status:'draft'})
const tools=[{label:'H2',before:'## ',after:''},{label:'B',before:'**',after:'**'},{label:'链接',before:'[',after:'](https://)'},{label:'图片',before:'![图片](',after:')'},{label:'视频',before:'<video controls src="',after:'"></video>'}]
const filtered=computed(()=>items.value.filter(x=>!search.value||`${x.title} ${x.slug} ${x.summary}`.toLowerCase().includes(search.value.toLowerCase())))
const previewHtml=computed(()=>DOMPurify.sanitize(marked.parse(form.content_markdown||'') as string,{ADD_TAGS:['video'],ADD_ATTR:['controls','src','preload']}))
const statusLabel=(s:string)=>({draft:'草稿',published:'已发布',offline:'已下线'}[s]||s)
function fill(t:Tutorial){selected.value=t;Object.assign(form,{slug:t.slug,title:t.title,summary:t.summary,category:t.category,content_markdown:t.content_markdown||t.content_html,is_public:t.is_public,sort_order:t.sort_order,status:t.status});preview.value=false}
function select(t:Tutorial){fill(t)}
function newTutorial(){selected.value=null;Object.assign(form,{slug:'new-tutorial',title:'新教程',summary:'',category:'getting-started',content_markdown:'# 新教程\n\n在这里填写教程正文。',is_public:false,sort_order:100,status:'draft'});preview.value=false}
function insert(before:string,after:string){const el=document.querySelector('textarea') as HTMLTextAreaElement|null;if(!el)return;const s=el.selectionStart,e=el.selectionEnd;form.content_markdown=form.content_markdown.slice(0,s)+before+form.content_markdown.slice(s,e)+after+form.content_markdown.slice(e);requestAnimationFrame(()=>el.focus())}
async function load(){const res=await listAdminTutorials({page:1,page_size:100});items.value=res.items;if(!selected.value&&items.value[0])fill(items.value[0])}
async function save(){saving.value=true;try{const input={...form,content_html:previewHtml.value};const saved=selected.value?await updateTutorial(selected.value.id,input):await createTutorial(input);if(saved.status!==form.status){await setTutorialStatus(saved.id,form.status)};appStore.showSuccess(form.status==='published'?'教程已发布':form.status==='offline'?'教程已下线':'教程已保存');await load()}catch(e:any){appStore.showError(e?.message||'保存失败')}finally{saving.value=false}}
async function remove(){if(!selected.value)return;if(!confirm('确认删除当前教程？'))return;await deleteTutorial(selected.value.id);appStore.showSuccess('教程已删除');newTutorial();await load()}
onMounted(load)
</script>

<style scoped>:deep(.tutorial-preview h1){font-size:2rem;font-weight:700}:deep(.tutorial-preview h2){font-size:1.4rem;font-weight:700;margin:1.5rem 0 .6rem}:deep(.tutorial-preview p),:deep(.tutorial-preview li){line-height:1.8;font-size:.95rem}:deep(.tutorial-preview ul){list-style:disc;padding-left:1.4rem}:deep(.tutorial-preview img),:deep(.tutorial-preview video){max-width:100%;margin:1rem auto;display:block;border-radius:.7rem}</style>
