// Code generated by ent, DO NOT EDIT.

package upstreamerrorrecord

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upstreamerrorrecord type in the database.
	Label = "upstream_error_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUpstreamType holds the string denoting the upstream_type field in the database.
	FieldUpstreamType = "upstream_type"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldErrorType holds the string denoting the error_type field in the database.
	FieldErrorType = "error_type"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldHTTPStatus holds the string denoting the http_status field in the database.
	FieldHTTPStatus = "http_status"
	// FieldOccurredAt holds the string denoting the occurred_at field in the database.
	FieldOccurredAt = "occurred_at"
	// Table holds the table name of the upstreamerrorrecord in the database.
	Table = "upstream_error_records"
)

// Columns holds all SQL columns for upstreamerrorrecord fields.
var Columns = []string{
	FieldID,
	FieldUpstreamType,
	FieldAccountID,
	FieldErrorType,
	FieldErrorMessage,
	FieldHTTPStatus,
	FieldOccurredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UpstreamTypeValidator is a validator for the "upstream_type" field. It is called by the builders before save.
	UpstreamTypeValidator func(string) error
	// ErrorTypeValidator is a validator for the "error_type" field. It is called by the builders before save.
	ErrorTypeValidator func(string) error
)

// OrderOption defines the ordering options for the UpstreamErrorRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUpstreamType orders the results by the upstream_type field.
func ByUpstreamType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamType, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByErrorType orders the results by the error_type field.
func ByErrorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorType, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByHTTPStatus orders the results by the http_status field.
func ByHTTPStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPStatus, opts...).ToFunc()
}

// ByOccurredAt orders the results by the occurred_at field.
func ByOccurredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccurredAt, opts...).ToFunc()
}
