// Code generated by ent, DO NOT EDIT.

package upstreamerrorrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLTE(FieldID, id))
}

// UpstreamType applies equality check predicate on the "upstream_type" field. It's identical to UpstreamTypeEQ.
func UpstreamType(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldUpstreamType, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldAccountID, v))
}

// ErrorType applies equality check predicate on the "error_type" field. It's identical to ErrorTypeEQ.
func ErrorType(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldErrorType, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldErrorMessage, v))
}

// HTTPStatus applies equality check predicate on the "http_status" field. It's identical to HTTPStatusEQ.
func HTTPStatus(v int) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldHTTPStatus, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldOccurredAt, v))
}

// UpstreamTypeEQ applies the EQ predicate on the "upstream_type" field.
func UpstreamTypeEQ(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldUpstreamType, v))
}

// UpstreamTypeNEQ applies the NEQ predicate on the "upstream_type" field.
func UpstreamTypeNEQ(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNEQ(FieldUpstreamType, v))
}

// UpstreamTypeIn applies the In predicate on the "upstream_type" field.
func UpstreamTypeIn(vs ...string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldIn(FieldUpstreamType, vs...))
}

// UpstreamTypeNotIn applies the NotIn predicate on the "upstream_type" field.
func UpstreamTypeNotIn(vs ...string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNotIn(FieldUpstreamType, vs...))
}

// UpstreamTypeGT applies the GT predicate on the "upstream_type" field.
func UpstreamTypeGT(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGT(FieldUpstreamType, v))
}

// UpstreamTypeGTE applies the GTE predicate on the "upstream_type" field.
func UpstreamTypeGTE(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGTE(FieldUpstreamType, v))
}

// UpstreamTypeLT applies the LT predicate on the "upstream_type" field.
func UpstreamTypeLT(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLT(FieldUpstreamType, v))
}

// UpstreamTypeLTE applies the LTE predicate on the "upstream_type" field.
func UpstreamTypeLTE(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLTE(FieldUpstreamType, v))
}

// UpstreamTypeContains applies the Contains predicate on the "upstream_type" field.
func UpstreamTypeContains(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldContains(FieldUpstreamType, v))
}

// UpstreamTypeHasPrefix applies the HasPrefix predicate on the "upstream_type" field.
func UpstreamTypeHasPrefix(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldHasPrefix(FieldUpstreamType, v))
}

// UpstreamTypeHasSuffix applies the HasSuffix predicate on the "upstream_type" field.
func UpstreamTypeHasSuffix(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldHasSuffix(FieldUpstreamType, v))
}

// UpstreamTypeEqualFold applies the EqualFold predicate on the "upstream_type" field.
func UpstreamTypeEqualFold(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEqualFold(FieldUpstreamType, v))
}

// UpstreamTypeContainsFold applies the ContainsFold predicate on the "upstream_type" field.
func UpstreamTypeContainsFold(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldContainsFold(FieldUpstreamType, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLTE(FieldAccountID, v))
}

// ErrorTypeEQ applies the EQ predicate on the "error_type" field.
func ErrorTypeEQ(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldErrorType, v))
}

// ErrorTypeNEQ applies the NEQ predicate on the "error_type" field.
func ErrorTypeNEQ(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNEQ(FieldErrorType, v))
}

// ErrorTypeIn applies the In predicate on the "error_type" field.
func ErrorTypeIn(vs ...string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldIn(FieldErrorType, vs...))
}

// ErrorTypeNotIn applies the NotIn predicate on the "error_type" field.
func ErrorTypeNotIn(vs ...string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNotIn(FieldErrorType, vs...))
}

// ErrorTypeGT applies the GT predicate on the "error_type" field.
func ErrorTypeGT(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGT(FieldErrorType, v))
}

// ErrorTypeGTE applies the GTE predicate on the "error_type" field.
func ErrorTypeGTE(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGTE(FieldErrorType, v))
}

// ErrorTypeLT applies the LT predicate on the "error_type" field.
func ErrorTypeLT(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLT(FieldErrorType, v))
}

// ErrorTypeLTE applies the LTE predicate on the "error_type" field.
func ErrorTypeLTE(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLTE(FieldErrorType, v))
}

// ErrorTypeContains applies the Contains predicate on the "error_type" field.
func ErrorTypeContains(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldContains(FieldErrorType, v))
}

// ErrorTypeHasPrefix applies the HasPrefix predicate on the "error_type" field.
func ErrorTypeHasPrefix(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldHasPrefix(FieldErrorType, v))
}

// ErrorTypeHasSuffix applies the HasSuffix predicate on the "error_type" field.
func ErrorTypeHasSuffix(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldHasSuffix(FieldErrorType, v))
}

// ErrorTypeEqualFold applies the EqualFold predicate on the "error_type" field.
func ErrorTypeEqualFold(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEqualFold(FieldErrorType, v))
}

// ErrorTypeContainsFold applies the ContainsFold predicate on the "error_type" field.
func ErrorTypeContainsFold(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldContainsFold(FieldErrorType, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldContainsFold(FieldErrorMessage, v))
}

// HTTPStatusEQ applies the EQ predicate on the "http_status" field.
func HTTPStatusEQ(v int) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldHTTPStatus, v))
}

// HTTPStatusNEQ applies the NEQ predicate on the "http_status" field.
func HTTPStatusNEQ(v int) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNEQ(FieldHTTPStatus, v))
}

// HTTPStatusIn applies the In predicate on the "http_status" field.
func HTTPStatusIn(vs ...int) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldIn(FieldHTTPStatus, vs...))
}

// HTTPStatusNotIn applies the NotIn predicate on the "http_status" field.
func HTTPStatusNotIn(vs ...int) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNotIn(FieldHTTPStatus, vs...))
}

// HTTPStatusGT applies the GT predicate on the "http_status" field.
func HTTPStatusGT(v int) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGT(FieldHTTPStatus, v))
}

// HTTPStatusGTE applies the GTE predicate on the "http_status" field.
func HTTPStatusGTE(v int) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGTE(FieldHTTPStatus, v))
}

// HTTPStatusLT applies the LT predicate on the "http_status" field.
func HTTPStatusLT(v int) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLT(FieldHTTPStatus, v))
}

// HTTPStatusLTE applies the LTE predicate on the "http_status" field.
func HTTPStatusLTE(v int) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLTE(FieldHTTPStatus, v))
}

// HTTPStatusIsNil applies the IsNil predicate on the "http_status" field.
func HTTPStatusIsNil() predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldIsNull(FieldHTTPStatus))
}

// HTTPStatusNotNil applies the NotNil predicate on the "http_status" field.
func HTTPStatusNotNil() predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNotNull(FieldHTTPStatus))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.FieldLTE(FieldOccurredAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamErrorRecord) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamErrorRecord) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamErrorRecord) predicate.UpstreamErrorRecord {
	return predicate.UpstreamErrorRecord(sql.NotPredicates(p))
}
