// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreambalancesnapshot"
)

// UpstreamBalanceSnapshotCreate is the builder for creating a UpstreamBalanceSnapshot entity.
type UpstreamBalanceSnapshotCreate struct {
	config
	mutation *UpstreamBalanceSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUpstreamType sets the "upstream_type" field.
func (_c *UpstreamBalanceSnapshotCreate) SetUpstreamType(v string) *UpstreamBalanceSnapshotCreate {
	_c.mutation.SetUpstreamType(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *UpstreamBalanceSnapshotCreate) SetAccountID(v int64) *UpstreamBalanceSnapshotCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetBalance sets the "balance" field.
func (_c *UpstreamBalanceSnapshotCreate) SetBalance(v float64) *UpstreamBalanceSnapshotCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *UpstreamBalanceSnapshotCreate) SetCurrency(v string) *UpstreamBalanceSnapshotCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *UpstreamBalanceSnapshotCreate) SetNillableCurrency(v *string) *UpstreamBalanceSnapshotCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetSnapshotAt sets the "snapshot_at" field.
func (_c *UpstreamBalanceSnapshotCreate) SetSnapshotAt(v time.Time) *UpstreamBalanceSnapshotCreate {
	_c.mutation.SetSnapshotAt(v)
	return _c
}

// SetNillableSnapshotAt sets the "snapshot_at" field if the given value is not nil.
func (_c *UpstreamBalanceSnapshotCreate) SetNillableSnapshotAt(v *time.Time) *UpstreamBalanceSnapshotCreate {
	if v != nil {
		_c.SetSnapshotAt(*v)
	}
	return _c
}

// Mutation returns the UpstreamBalanceSnapshotMutation object of the builder.
func (_c *UpstreamBalanceSnapshotCreate) Mutation() *UpstreamBalanceSnapshotMutation {
	return _c.mutation
}

// Save creates the UpstreamBalanceSnapshot in the database.
func (_c *UpstreamBalanceSnapshotCreate) Save(ctx context.Context) (*UpstreamBalanceSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamBalanceSnapshotCreate) SaveX(ctx context.Context) *UpstreamBalanceSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamBalanceSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamBalanceSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamBalanceSnapshotCreate) defaults() {
	if _, ok := _c.mutation.Currency(); !ok {
		v := upstreambalancesnapshot.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.SnapshotAt(); !ok {
		v := upstreambalancesnapshot.DefaultSnapshotAt()
		_c.mutation.SetSnapshotAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamBalanceSnapshotCreate) check() error {
	if _, ok := _c.mutation.UpstreamType(); !ok {
		return &ValidationError{Name: "upstream_type", err: errors.New(`ent: missing required field "UpstreamBalanceSnapshot.upstream_type"`)}
	}
	if v, ok := _c.mutation.UpstreamType(); ok {
		if err := upstreambalancesnapshot.UpstreamTypeValidator(v); err != nil {
			return &ValidationError{Name: "upstream_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamBalanceSnapshot.upstream_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "UpstreamBalanceSnapshot.account_id"`)}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "UpstreamBalanceSnapshot.balance"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "UpstreamBalanceSnapshot.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := upstreambalancesnapshot.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "UpstreamBalanceSnapshot.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SnapshotAt(); !ok {
		return &ValidationError{Name: "snapshot_at", err: errors.New(`ent: missing required field "UpstreamBalanceSnapshot.snapshot_at"`)}
	}
	return nil
}

func (_c *UpstreamBalanceSnapshotCreate) sqlSave(ctx context.Context) (*UpstreamBalanceSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamBalanceSnapshotCreate) createSpec() (*UpstreamBalanceSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamBalanceSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreambalancesnapshot.Table, sqlgraph.NewFieldSpec(upstreambalancesnapshot.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UpstreamType(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldUpstreamType, field.TypeString, value)
		_node.UpstreamType = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.SnapshotAt(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldSnapshotAt, field.TypeTime, value)
		_node.SnapshotAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamBalanceSnapshot.Create().
//		SetUpstreamType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamBalanceSnapshotUpsert) {
//			SetUpstreamType(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamBalanceSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamBalanceSnapshotUpsertOne {
	_c.conflict = opts
	return &UpstreamBalanceSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamBalanceSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamBalanceSnapshotCreate) OnConflictColumns(columns ...string) *UpstreamBalanceSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamBalanceSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamBalanceSnapshotUpsertOne is the builder for "upsert"-ing
	//  one UpstreamBalanceSnapshot node.
	UpstreamBalanceSnapshotUpsertOne struct {
		create *UpstreamBalanceSnapshotCreate
	}

	// UpstreamBalanceSnapshotUpsert is the "OnConflict" setter.
	UpstreamBalanceSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpstreamType sets the "upstream_type" field.
func (u *UpstreamBalanceSnapshotUpsert) SetUpstreamType(v string) *UpstreamBalanceSnapshotUpsert {
	u.Set(upstreambalancesnapshot.FieldUpstreamType, v)
	return u
}

// UpdateUpstreamType sets the "upstream_type" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsert) UpdateUpstreamType() *UpstreamBalanceSnapshotUpsert {
	u.SetExcluded(upstreambalancesnapshot.FieldUpstreamType)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *UpstreamBalanceSnapshotUpsert) SetAccountID(v int64) *UpstreamBalanceSnapshotUpsert {
	u.Set(upstreambalancesnapshot.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsert) UpdateAccountID() *UpstreamBalanceSnapshotUpsert {
	u.SetExcluded(upstreambalancesnapshot.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *UpstreamBalanceSnapshotUpsert) AddAccountID(v int64) *UpstreamBalanceSnapshotUpsert {
	u.Add(upstreambalancesnapshot.FieldAccountID, v)
	return u
}

// SetBalance sets the "balance" field.
func (u *UpstreamBalanceSnapshotUpsert) SetBalance(v float64) *UpstreamBalanceSnapshotUpsert {
	u.Set(upstreambalancesnapshot.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsert) UpdateBalance() *UpstreamBalanceSnapshotUpsert {
	u.SetExcluded(upstreambalancesnapshot.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *UpstreamBalanceSnapshotUpsert) AddBalance(v float64) *UpstreamBalanceSnapshotUpsert {
	u.Add(upstreambalancesnapshot.FieldBalance, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *UpstreamBalanceSnapshotUpsert) SetCurrency(v string) *UpstreamBalanceSnapshotUpsert {
	u.Set(upstreambalancesnapshot.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsert) UpdateCurrency() *UpstreamBalanceSnapshotUpsert {
	u.SetExcluded(upstreambalancesnapshot.FieldCurrency)
	return u
}

// SetSnapshotAt sets the "snapshot_at" field.
func (u *UpstreamBalanceSnapshotUpsert) SetSnapshotAt(v time.Time) *UpstreamBalanceSnapshotUpsert {
	u.Set(upstreambalancesnapshot.FieldSnapshotAt, v)
	return u
}

// UpdateSnapshotAt sets the "snapshot_at" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsert) UpdateSnapshotAt() *UpstreamBalanceSnapshotUpsert {
	u.SetExcluded(upstreambalancesnapshot.FieldSnapshotAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamBalanceSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamBalanceSnapshotUpsertOne) UpdateNewValues() *UpstreamBalanceSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamBalanceSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamBalanceSnapshotUpsertOne) Ignore() *UpstreamBalanceSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamBalanceSnapshotUpsertOne) DoNothing() *UpstreamBalanceSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamBalanceSnapshotCreate.OnConflict
// documentation for more info.
func (u *UpstreamBalanceSnapshotUpsertOne) Update(set func(*UpstreamBalanceSnapshotUpsert)) *UpstreamBalanceSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamBalanceSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpstreamType sets the "upstream_type" field.
func (u *UpstreamBalanceSnapshotUpsertOne) SetUpstreamType(v string) *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.SetUpstreamType(v)
	})
}

// UpdateUpstreamType sets the "upstream_type" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsertOne) UpdateUpstreamType() *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.UpdateUpstreamType()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UpstreamBalanceSnapshotUpsertOne) SetAccountID(v int64) *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UpstreamBalanceSnapshotUpsertOne) AddAccountID(v int64) *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsertOne) UpdateAccountID() *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.UpdateAccountID()
	})
}

// SetBalance sets the "balance" field.
func (u *UpstreamBalanceSnapshotUpsertOne) SetBalance(v float64) *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *UpstreamBalanceSnapshotUpsertOne) AddBalance(v float64) *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsertOne) UpdateBalance() *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.UpdateBalance()
	})
}

// SetCurrency sets the "currency" field.
func (u *UpstreamBalanceSnapshotUpsertOne) SetCurrency(v string) *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsertOne) UpdateCurrency() *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.UpdateCurrency()
	})
}

// SetSnapshotAt sets the "snapshot_at" field.
func (u *UpstreamBalanceSnapshotUpsertOne) SetSnapshotAt(v time.Time) *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.SetSnapshotAt(v)
	})
}

// UpdateSnapshotAt sets the "snapshot_at" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsertOne) UpdateSnapshotAt() *UpstreamBalanceSnapshotUpsertOne {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.UpdateSnapshotAt()
	})
}

// Exec executes the query.
func (u *UpstreamBalanceSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamBalanceSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamBalanceSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamBalanceSnapshotUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamBalanceSnapshotUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamBalanceSnapshotCreateBulk is the builder for creating many UpstreamBalanceSnapshot entities in bulk.
type UpstreamBalanceSnapshotCreateBulk struct {
	config
	err      error
	builders []*UpstreamBalanceSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamBalanceSnapshot entities in the database.
func (_c *UpstreamBalanceSnapshotCreateBulk) Save(ctx context.Context) ([]*UpstreamBalanceSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamBalanceSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamBalanceSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamBalanceSnapshotCreateBulk) SaveX(ctx context.Context) []*UpstreamBalanceSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamBalanceSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamBalanceSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamBalanceSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamBalanceSnapshotUpsert) {
//			SetUpstreamType(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamBalanceSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamBalanceSnapshotUpsertBulk {
	_c.conflict = opts
	return &UpstreamBalanceSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamBalanceSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamBalanceSnapshotCreateBulk) OnConflictColumns(columns ...string) *UpstreamBalanceSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamBalanceSnapshotUpsertBulk{
		create: _c,
	}
}

// UpstreamBalanceSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamBalanceSnapshot nodes.
type UpstreamBalanceSnapshotUpsertBulk struct {
	create *UpstreamBalanceSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamBalanceSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamBalanceSnapshotUpsertBulk) UpdateNewValues() *UpstreamBalanceSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamBalanceSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamBalanceSnapshotUpsertBulk) Ignore() *UpstreamBalanceSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamBalanceSnapshotUpsertBulk) DoNothing() *UpstreamBalanceSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamBalanceSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamBalanceSnapshotUpsertBulk) Update(set func(*UpstreamBalanceSnapshotUpsert)) *UpstreamBalanceSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamBalanceSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpstreamType sets the "upstream_type" field.
func (u *UpstreamBalanceSnapshotUpsertBulk) SetUpstreamType(v string) *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.SetUpstreamType(v)
	})
}

// UpdateUpstreamType sets the "upstream_type" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsertBulk) UpdateUpstreamType() *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.UpdateUpstreamType()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UpstreamBalanceSnapshotUpsertBulk) SetAccountID(v int64) *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UpstreamBalanceSnapshotUpsertBulk) AddAccountID(v int64) *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsertBulk) UpdateAccountID() *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.UpdateAccountID()
	})
}

// SetBalance sets the "balance" field.
func (u *UpstreamBalanceSnapshotUpsertBulk) SetBalance(v float64) *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *UpstreamBalanceSnapshotUpsertBulk) AddBalance(v float64) *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsertBulk) UpdateBalance() *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.UpdateBalance()
	})
}

// SetCurrency sets the "currency" field.
func (u *UpstreamBalanceSnapshotUpsertBulk) SetCurrency(v string) *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsertBulk) UpdateCurrency() *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.UpdateCurrency()
	})
}

// SetSnapshotAt sets the "snapshot_at" field.
func (u *UpstreamBalanceSnapshotUpsertBulk) SetSnapshotAt(v time.Time) *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.SetSnapshotAt(v)
	})
}

// UpdateSnapshotAt sets the "snapshot_at" field to the value that was provided on create.
func (u *UpstreamBalanceSnapshotUpsertBulk) UpdateSnapshotAt() *UpstreamBalanceSnapshotUpsertBulk {
	return u.Update(func(s *UpstreamBalanceSnapshotUpsert) {
		s.UpdateSnapshotAt()
	})
}

// Exec executes the query.
func (u *UpstreamBalanceSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamBalanceSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamBalanceSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamBalanceSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
