// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreammonitorupstream"
)

// UpstreamMonitorUpstream is the model entity for the UpstreamMonitorUpstream schema.
type UpstreamMonitorUpstream struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// BaseURL holds the value of the "base_url" field.
	BaseURL string `json:"base_url,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// UpstreamType holds the value of the "upstream_type" field.
	UpstreamType upstreammonitorupstream.UpstreamType `json:"upstream_type,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken *string `json:"-"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamMonitorUpstream) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreammonitorupstream.FieldEnabled:
			values[i] = new(sql.NullBool)
		case upstreammonitorupstream.FieldID:
			values[i] = new(sql.NullInt64)
		case upstreammonitorupstream.FieldBaseURL, upstreammonitorupstream.FieldName, upstreammonitorupstream.FieldUpstreamType, upstreammonitorupstream.FieldAccessToken:
			values[i] = new(sql.NullString)
		case upstreammonitorupstream.FieldCreatedAt, upstreammonitorupstream.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamMonitorUpstream fields.
func (_m *UpstreamMonitorUpstream) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreammonitorupstream.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreammonitorupstream.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case upstreammonitorupstream.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstreammonitorupstream.FieldUpstreamType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_type", values[i])
			} else if value.Valid {
				_m.UpstreamType = upstreammonitorupstream.UpstreamType(value.String)
			}
		case upstreammonitorupstream.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				_m.AccessToken = new(string)
				*_m.AccessToken = value.String
			}
		case upstreammonitorupstream.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case upstreammonitorupstream.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreammonitorupstream.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamMonitorUpstream.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamMonitorUpstream) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UpstreamMonitorUpstream.
// Note that you need to call UpstreamMonitorUpstream.Unwrap() before calling this method if this UpstreamMonitorUpstream
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamMonitorUpstream) Update() *UpstreamMonitorUpstreamUpdateOne {
	return NewUpstreamMonitorUpstreamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamMonitorUpstream entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamMonitorUpstream) Unwrap() *UpstreamMonitorUpstream {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamMonitorUpstream is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamMonitorUpstream) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamMonitorUpstream(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("upstream_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamType))
	builder.WriteString(", ")
	builder.WriteString("access_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamMonitorUpstreams is a parsable slice of UpstreamMonitorUpstream.
type UpstreamMonitorUpstreams []*UpstreamMonitorUpstream
