// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamerrorrecord"
)

// UpstreamErrorRecord is the model entity for the UpstreamErrorRecord schema.
type UpstreamErrorRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UpstreamType holds the value of the "upstream_type" field.
	UpstreamType string `json:"upstream_type,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// ErrorType holds the value of the "error_type" field.
	ErrorType string `json:"error_type,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// HTTPStatus holds the value of the "http_status" field.
	HTTPStatus *int `json:"http_status,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt   time.Time `json:"occurred_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamErrorRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamerrorrecord.FieldID, upstreamerrorrecord.FieldAccountID, upstreamerrorrecord.FieldHTTPStatus:
			values[i] = new(sql.NullInt64)
		case upstreamerrorrecord.FieldUpstreamType, upstreamerrorrecord.FieldErrorType, upstreamerrorrecord.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case upstreamerrorrecord.FieldOccurredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamErrorRecord fields.
func (_m *UpstreamErrorRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamerrorrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamerrorrecord.FieldUpstreamType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_type", values[i])
			} else if value.Valid {
				_m.UpstreamType = value.String
			}
		case upstreamerrorrecord.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case upstreamerrorrecord.FieldErrorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_type", values[i])
			} else if value.Valid {
				_m.ErrorType = value.String
			}
		case upstreamerrorrecord.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case upstreamerrorrecord.FieldHTTPStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field http_status", values[i])
			} else if value.Valid {
				_m.HTTPStatus = new(int)
				*_m.HTTPStatus = int(value.Int64)
			}
		case upstreamerrorrecord.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamErrorRecord.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamErrorRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UpstreamErrorRecord.
// Note that you need to call UpstreamErrorRecord.Unwrap() before calling this method if this UpstreamErrorRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamErrorRecord) Update() *UpstreamErrorRecordUpdateOne {
	return NewUpstreamErrorRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamErrorRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamErrorRecord) Unwrap() *UpstreamErrorRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamErrorRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamErrorRecord) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamErrorRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("upstream_type=")
	builder.WriteString(_m.UpstreamType)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("error_type=")
	builder.WriteString(_m.ErrorType)
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.HTTPStatus; v != nil {
		builder.WriteString("http_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamErrorRecords is a parsable slice of UpstreamErrorRecord.
type UpstreamErrorRecords []*UpstreamErrorRecord
