// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreammonitorupstream"
)

// UpstreamMonitorUpstreamUpdate is the builder for updating UpstreamMonitorUpstream entities.
type UpstreamMonitorUpstreamUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamMonitorUpstreamMutation
}

// Where appends a list predicates to the UpstreamMonitorUpstreamUpdate builder.
func (_u *UpstreamMonitorUpstreamUpdate) Where(ps ...predicate.UpstreamMonitorUpstream) *UpstreamMonitorUpstreamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamMonitorUpstreamUpdate) SetBaseURL(v string) *UpstreamMonitorUpstreamUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamMonitorUpstreamUpdate) SetNillableBaseURL(v *string) *UpstreamMonitorUpstreamUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamMonitorUpstreamUpdate) SetName(v string) *UpstreamMonitorUpstreamUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamMonitorUpstreamUpdate) SetNillableName(v *string) *UpstreamMonitorUpstreamUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUpstreamType sets the "upstream_type" field.
func (_u *UpstreamMonitorUpstreamUpdate) SetUpstreamType(v upstreammonitorupstream.UpstreamType) *UpstreamMonitorUpstreamUpdate {
	_u.mutation.SetUpstreamType(v)
	return _u
}

// SetNillableUpstreamType sets the "upstream_type" field if the given value is not nil.
func (_u *UpstreamMonitorUpstreamUpdate) SetNillableUpstreamType(v *upstreammonitorupstream.UpstreamType) *UpstreamMonitorUpstreamUpdate {
	if v != nil {
		_u.SetUpstreamType(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamMonitorUpstreamUpdate) SetEnabled(v bool) *UpstreamMonitorUpstreamUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamMonitorUpstreamUpdate) SetNillableEnabled(v *bool) *UpstreamMonitorUpstreamUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamMonitorUpstreamUpdate) SetUpdatedAt(v time.Time) *UpstreamMonitorUpstreamUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UpstreamMonitorUpstreamMutation object of the builder.
func (_u *UpstreamMonitorUpstreamUpdate) Mutation() *UpstreamMonitorUpstreamMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamMonitorUpstreamUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamMonitorUpstreamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamMonitorUpstreamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamMonitorUpstreamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamMonitorUpstreamUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreammonitorupstream.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamMonitorUpstreamUpdate) check() error {
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreammonitorupstream.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamMonitorUpstream.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreammonitorupstream.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamMonitorUpstream.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamType(); ok {
		if err := upstreammonitorupstream.UpstreamTypeValidator(v); err != nil {
			return &ValidationError{Name: "upstream_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamMonitorUpstream.upstream_type": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamMonitorUpstreamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreammonitorupstream.Table, upstreammonitorupstream.Columns, sqlgraph.NewFieldSpec(upstreammonitorupstream.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreammonitorupstream.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreammonitorupstream.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamType(); ok {
		_spec.SetField(upstreammonitorupstream.FieldUpstreamType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstreammonitorupstream.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreammonitorupstream.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreammonitorupstream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamMonitorUpstreamUpdateOne is the builder for updating a single UpstreamMonitorUpstream entity.
type UpstreamMonitorUpstreamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamMonitorUpstreamMutation
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamMonitorUpstreamUpdateOne) SetBaseURL(v string) *UpstreamMonitorUpstreamUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamMonitorUpstreamUpdateOne) SetNillableBaseURL(v *string) *UpstreamMonitorUpstreamUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamMonitorUpstreamUpdateOne) SetName(v string) *UpstreamMonitorUpstreamUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamMonitorUpstreamUpdateOne) SetNillableName(v *string) *UpstreamMonitorUpstreamUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUpstreamType sets the "upstream_type" field.
func (_u *UpstreamMonitorUpstreamUpdateOne) SetUpstreamType(v upstreammonitorupstream.UpstreamType) *UpstreamMonitorUpstreamUpdateOne {
	_u.mutation.SetUpstreamType(v)
	return _u
}

// SetNillableUpstreamType sets the "upstream_type" field if the given value is not nil.
func (_u *UpstreamMonitorUpstreamUpdateOne) SetNillableUpstreamType(v *upstreammonitorupstream.UpstreamType) *UpstreamMonitorUpstreamUpdateOne {
	if v != nil {
		_u.SetUpstreamType(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamMonitorUpstreamUpdateOne) SetEnabled(v bool) *UpstreamMonitorUpstreamUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamMonitorUpstreamUpdateOne) SetNillableEnabled(v *bool) *UpstreamMonitorUpstreamUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamMonitorUpstreamUpdateOne) SetUpdatedAt(v time.Time) *UpstreamMonitorUpstreamUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UpstreamMonitorUpstreamMutation object of the builder.
func (_u *UpstreamMonitorUpstreamUpdateOne) Mutation() *UpstreamMonitorUpstreamMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamMonitorUpstreamUpdate builder.
func (_u *UpstreamMonitorUpstreamUpdateOne) Where(ps ...predicate.UpstreamMonitorUpstream) *UpstreamMonitorUpstreamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamMonitorUpstreamUpdateOne) Select(field string, fields ...string) *UpstreamMonitorUpstreamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamMonitorUpstream entity.
func (_u *UpstreamMonitorUpstreamUpdateOne) Save(ctx context.Context) (*UpstreamMonitorUpstream, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamMonitorUpstreamUpdateOne) SaveX(ctx context.Context) *UpstreamMonitorUpstream {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamMonitorUpstreamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamMonitorUpstreamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamMonitorUpstreamUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreammonitorupstream.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamMonitorUpstreamUpdateOne) check() error {
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreammonitorupstream.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamMonitorUpstream.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreammonitorupstream.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamMonitorUpstream.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamType(); ok {
		if err := upstreammonitorupstream.UpstreamTypeValidator(v); err != nil {
			return &ValidationError{Name: "upstream_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamMonitorUpstream.upstream_type": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamMonitorUpstreamUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamMonitorUpstream, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreammonitorupstream.Table, upstreammonitorupstream.Columns, sqlgraph.NewFieldSpec(upstreammonitorupstream.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamMonitorUpstream.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreammonitorupstream.FieldID)
		for _, f := range fields {
			if !upstreammonitorupstream.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreammonitorupstream.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreammonitorupstream.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreammonitorupstream.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamType(); ok {
		_spec.SetField(upstreammonitorupstream.FieldUpstreamType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstreammonitorupstream.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreammonitorupstream.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UpstreamMonitorUpstream{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreammonitorupstream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
