// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreambalancesnapshot"
)

// UpstreamBalanceSnapshotUpdate is the builder for updating UpstreamBalanceSnapshot entities.
type UpstreamBalanceSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamBalanceSnapshotMutation
}

// Where appends a list predicates to the UpstreamBalanceSnapshotUpdate builder.
func (_u *UpstreamBalanceSnapshotUpdate) Where(ps ...predicate.UpstreamBalanceSnapshot) *UpstreamBalanceSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpstreamType sets the "upstream_type" field.
func (_u *UpstreamBalanceSnapshotUpdate) SetUpstreamType(v string) *UpstreamBalanceSnapshotUpdate {
	_u.mutation.SetUpstreamType(v)
	return _u
}

// SetNillableUpstreamType sets the "upstream_type" field if the given value is not nil.
func (_u *UpstreamBalanceSnapshotUpdate) SetNillableUpstreamType(v *string) *UpstreamBalanceSnapshotUpdate {
	if v != nil {
		_u.SetUpstreamType(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UpstreamBalanceSnapshotUpdate) SetAccountID(v int64) *UpstreamBalanceSnapshotUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UpstreamBalanceSnapshotUpdate) SetNillableAccountID(v *int64) *UpstreamBalanceSnapshotUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UpstreamBalanceSnapshotUpdate) AddAccountID(v int64) *UpstreamBalanceSnapshotUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *UpstreamBalanceSnapshotUpdate) SetBalance(v float64) *UpstreamBalanceSnapshotUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UpstreamBalanceSnapshotUpdate) SetNillableBalance(v *float64) *UpstreamBalanceSnapshotUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UpstreamBalanceSnapshotUpdate) AddBalance(v float64) *UpstreamBalanceSnapshotUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *UpstreamBalanceSnapshotUpdate) SetCurrency(v string) *UpstreamBalanceSnapshotUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *UpstreamBalanceSnapshotUpdate) SetNillableCurrency(v *string) *UpstreamBalanceSnapshotUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetSnapshotAt sets the "snapshot_at" field.
func (_u *UpstreamBalanceSnapshotUpdate) SetSnapshotAt(v time.Time) *UpstreamBalanceSnapshotUpdate {
	_u.mutation.SetSnapshotAt(v)
	return _u
}

// SetNillableSnapshotAt sets the "snapshot_at" field if the given value is not nil.
func (_u *UpstreamBalanceSnapshotUpdate) SetNillableSnapshotAt(v *time.Time) *UpstreamBalanceSnapshotUpdate {
	if v != nil {
		_u.SetSnapshotAt(*v)
	}
	return _u
}

// Mutation returns the UpstreamBalanceSnapshotMutation object of the builder.
func (_u *UpstreamBalanceSnapshotUpdate) Mutation() *UpstreamBalanceSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamBalanceSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamBalanceSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamBalanceSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamBalanceSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamBalanceSnapshotUpdate) check() error {
	if v, ok := _u.mutation.UpstreamType(); ok {
		if err := upstreambalancesnapshot.UpstreamTypeValidator(v); err != nil {
			return &ValidationError{Name: "upstream_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamBalanceSnapshot.upstream_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := upstreambalancesnapshot.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "UpstreamBalanceSnapshot.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamBalanceSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreambalancesnapshot.Table, upstreambalancesnapshot.Columns, sqlgraph.NewFieldSpec(upstreambalancesnapshot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpstreamType(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldUpstreamType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(upstreambalancesnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(upstreambalancesnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.SnapshotAt(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldSnapshotAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreambalancesnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamBalanceSnapshotUpdateOne is the builder for updating a single UpstreamBalanceSnapshot entity.
type UpstreamBalanceSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamBalanceSnapshotMutation
}

// SetUpstreamType sets the "upstream_type" field.
func (_u *UpstreamBalanceSnapshotUpdateOne) SetUpstreamType(v string) *UpstreamBalanceSnapshotUpdateOne {
	_u.mutation.SetUpstreamType(v)
	return _u
}

// SetNillableUpstreamType sets the "upstream_type" field if the given value is not nil.
func (_u *UpstreamBalanceSnapshotUpdateOne) SetNillableUpstreamType(v *string) *UpstreamBalanceSnapshotUpdateOne {
	if v != nil {
		_u.SetUpstreamType(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UpstreamBalanceSnapshotUpdateOne) SetAccountID(v int64) *UpstreamBalanceSnapshotUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UpstreamBalanceSnapshotUpdateOne) SetNillableAccountID(v *int64) *UpstreamBalanceSnapshotUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UpstreamBalanceSnapshotUpdateOne) AddAccountID(v int64) *UpstreamBalanceSnapshotUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *UpstreamBalanceSnapshotUpdateOne) SetBalance(v float64) *UpstreamBalanceSnapshotUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UpstreamBalanceSnapshotUpdateOne) SetNillableBalance(v *float64) *UpstreamBalanceSnapshotUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UpstreamBalanceSnapshotUpdateOne) AddBalance(v float64) *UpstreamBalanceSnapshotUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *UpstreamBalanceSnapshotUpdateOne) SetCurrency(v string) *UpstreamBalanceSnapshotUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *UpstreamBalanceSnapshotUpdateOne) SetNillableCurrency(v *string) *UpstreamBalanceSnapshotUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetSnapshotAt sets the "snapshot_at" field.
func (_u *UpstreamBalanceSnapshotUpdateOne) SetSnapshotAt(v time.Time) *UpstreamBalanceSnapshotUpdateOne {
	_u.mutation.SetSnapshotAt(v)
	return _u
}

// SetNillableSnapshotAt sets the "snapshot_at" field if the given value is not nil.
func (_u *UpstreamBalanceSnapshotUpdateOne) SetNillableSnapshotAt(v *time.Time) *UpstreamBalanceSnapshotUpdateOne {
	if v != nil {
		_u.SetSnapshotAt(*v)
	}
	return _u
}

// Mutation returns the UpstreamBalanceSnapshotMutation object of the builder.
func (_u *UpstreamBalanceSnapshotUpdateOne) Mutation() *UpstreamBalanceSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamBalanceSnapshotUpdate builder.
func (_u *UpstreamBalanceSnapshotUpdateOne) Where(ps ...predicate.UpstreamBalanceSnapshot) *UpstreamBalanceSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamBalanceSnapshotUpdateOne) Select(field string, fields ...string) *UpstreamBalanceSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamBalanceSnapshot entity.
func (_u *UpstreamBalanceSnapshotUpdateOne) Save(ctx context.Context) (*UpstreamBalanceSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamBalanceSnapshotUpdateOne) SaveX(ctx context.Context) *UpstreamBalanceSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamBalanceSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamBalanceSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamBalanceSnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.UpstreamType(); ok {
		if err := upstreambalancesnapshot.UpstreamTypeValidator(v); err != nil {
			return &ValidationError{Name: "upstream_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamBalanceSnapshot.upstream_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := upstreambalancesnapshot.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "UpstreamBalanceSnapshot.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamBalanceSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamBalanceSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreambalancesnapshot.Table, upstreambalancesnapshot.Columns, sqlgraph.NewFieldSpec(upstreambalancesnapshot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamBalanceSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreambalancesnapshot.FieldID)
		for _, f := range fields {
			if !upstreambalancesnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreambalancesnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpstreamType(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldUpstreamType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(upstreambalancesnapshot.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(upstreambalancesnapshot.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.SnapshotAt(); ok {
		_spec.SetField(upstreambalancesnapshot.FieldSnapshotAt, field.TypeTime, value)
	}
	_node = &UpstreamBalanceSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreambalancesnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
