// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreambalancesnapshot"
)

// UpstreamBalanceSnapshot is the model entity for the UpstreamBalanceSnapshot schema.
type UpstreamBalanceSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UpstreamType holds the value of the "upstream_type" field.
	UpstreamType string `json:"upstream_type,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance float64 `json:"balance,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// SnapshotAt holds the value of the "snapshot_at" field.
	SnapshotAt   time.Time `json:"snapshot_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamBalanceSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreambalancesnapshot.FieldBalance:
			values[i] = new(sql.NullFloat64)
		case upstreambalancesnapshot.FieldID, upstreambalancesnapshot.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case upstreambalancesnapshot.FieldUpstreamType, upstreambalancesnapshot.FieldCurrency:
			values[i] = new(sql.NullString)
		case upstreambalancesnapshot.FieldSnapshotAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamBalanceSnapshot fields.
func (_m *UpstreamBalanceSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreambalancesnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreambalancesnapshot.FieldUpstreamType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_type", values[i])
			} else if value.Valid {
				_m.UpstreamType = value.String
			}
		case upstreambalancesnapshot.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case upstreambalancesnapshot.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = value.Float64
			}
		case upstreambalancesnapshot.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case upstreambalancesnapshot.FieldSnapshotAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_at", values[i])
			} else if value.Valid {
				_m.SnapshotAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamBalanceSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamBalanceSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UpstreamBalanceSnapshot.
// Note that you need to call UpstreamBalanceSnapshot.Unwrap() before calling this method if this UpstreamBalanceSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamBalanceSnapshot) Update() *UpstreamBalanceSnapshotUpdateOne {
	return NewUpstreamBalanceSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamBalanceSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamBalanceSnapshot) Unwrap() *UpstreamBalanceSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamBalanceSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamBalanceSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamBalanceSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("upstream_type=")
	builder.WriteString(_m.UpstreamType)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("snapshot_at=")
	builder.WriteString(_m.SnapshotAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamBalanceSnapshots is a parsable slice of UpstreamBalanceSnapshot.
type UpstreamBalanceSnapshots []*UpstreamBalanceSnapshot
