// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreambalancesnapshot"
)

// UpstreamBalanceSnapshotDelete is the builder for deleting a UpstreamBalanceSnapshot entity.
type UpstreamBalanceSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *UpstreamBalanceSnapshotMutation
}

// Where appends a list predicates to the UpstreamBalanceSnapshotDelete builder.
func (_d *UpstreamBalanceSnapshotDelete) Where(ps ...predicate.UpstreamBalanceSnapshot) *UpstreamBalanceSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UpstreamBalanceSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpstreamBalanceSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UpstreamBalanceSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upstreambalancesnapshot.Table, sqlgraph.NewFieldSpec(upstreambalancesnapshot.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UpstreamBalanceSnapshotDeleteOne is the builder for deleting a single UpstreamBalanceSnapshot entity.
type UpstreamBalanceSnapshotDeleteOne struct {
	_d *UpstreamBalanceSnapshotDelete
}

// Where appends a list predicates to the UpstreamBalanceSnapshotDelete builder.
func (_d *UpstreamBalanceSnapshotDeleteOne) Where(ps ...predicate.UpstreamBalanceSnapshot) *UpstreamBalanceSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UpstreamBalanceSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upstreambalancesnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpstreamBalanceSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
