// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreammonitorupstream"
)

// UpstreamMonitorUpstreamCreate is the builder for creating a UpstreamMonitorUpstream entity.
type UpstreamMonitorUpstreamCreate struct {
	config
	mutation *UpstreamMonitorUpstreamMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBaseURL sets the "base_url" field.
func (_c *UpstreamMonitorUpstreamCreate) SetBaseURL(v string) *UpstreamMonitorUpstreamCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetName sets the "name" field.
func (_c *UpstreamMonitorUpstreamCreate) SetName(v string) *UpstreamMonitorUpstreamCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *UpstreamMonitorUpstreamCreate) SetNillableName(v *string) *UpstreamMonitorUpstreamCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetUpstreamType sets the "upstream_type" field.
func (_c *UpstreamMonitorUpstreamCreate) SetUpstreamType(v upstreammonitorupstream.UpstreamType) *UpstreamMonitorUpstreamCreate {
	_c.mutation.SetUpstreamType(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UpstreamMonitorUpstreamCreate) SetEnabled(v bool) *UpstreamMonitorUpstreamCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UpstreamMonitorUpstreamCreate) SetNillableEnabled(v *bool) *UpstreamMonitorUpstreamCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamMonitorUpstreamCreate) SetCreatedAt(v time.Time) *UpstreamMonitorUpstreamCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamMonitorUpstreamCreate) SetNillableCreatedAt(v *time.Time) *UpstreamMonitorUpstreamCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamMonitorUpstreamCreate) SetUpdatedAt(v time.Time) *UpstreamMonitorUpstreamCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamMonitorUpstreamCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamMonitorUpstreamCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UpstreamMonitorUpstreamMutation object of the builder.
func (_c *UpstreamMonitorUpstreamCreate) Mutation() *UpstreamMonitorUpstreamMutation {
	return _c.mutation
}

// Save creates the UpstreamMonitorUpstream in the database.
func (_c *UpstreamMonitorUpstreamCreate) Save(ctx context.Context) (*UpstreamMonitorUpstream, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamMonitorUpstreamCreate) SaveX(ctx context.Context) *UpstreamMonitorUpstream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamMonitorUpstreamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamMonitorUpstreamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamMonitorUpstreamCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := upstreammonitorupstream.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := upstreammonitorupstream.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := upstreammonitorupstream.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := upstreammonitorupstream.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamMonitorUpstreamCreate) check() error {
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "UpstreamMonitorUpstream.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := upstreammonitorupstream.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamMonitorUpstream.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpstreamMonitorUpstream.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := upstreammonitorupstream.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamMonitorUpstream.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamType(); !ok {
		return &ValidationError{Name: "upstream_type", err: errors.New(`ent: missing required field "UpstreamMonitorUpstream.upstream_type"`)}
	}
	if v, ok := _c.mutation.UpstreamType(); ok {
		if err := upstreammonitorupstream.UpstreamTypeValidator(v); err != nil {
			return &ValidationError{Name: "upstream_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamMonitorUpstream.upstream_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UpstreamMonitorUpstream.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamMonitorUpstream.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamMonitorUpstream.updated_at"`)}
	}
	return nil
}

func (_c *UpstreamMonitorUpstreamCreate) sqlSave(ctx context.Context) (*UpstreamMonitorUpstream, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamMonitorUpstreamCreate) createSpec() (*UpstreamMonitorUpstream, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamMonitorUpstream{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreammonitorupstream.Table, sqlgraph.NewFieldSpec(upstreammonitorupstream.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(upstreammonitorupstream.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstreammonitorupstream.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.UpstreamType(); ok {
		_spec.SetField(upstreammonitorupstream.FieldUpstreamType, field.TypeEnum, value)
		_node.UpstreamType = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(upstreammonitorupstream.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreammonitorupstream.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreammonitorupstream.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamMonitorUpstream.Create().
//		SetBaseURL(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamMonitorUpstreamUpsert) {
//			SetBaseURL(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamMonitorUpstreamCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamMonitorUpstreamUpsertOne {
	_c.conflict = opts
	return &UpstreamMonitorUpstreamUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamMonitorUpstream.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamMonitorUpstreamCreate) OnConflictColumns(columns ...string) *UpstreamMonitorUpstreamUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamMonitorUpstreamUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamMonitorUpstreamUpsertOne is the builder for "upsert"-ing
	//  one UpstreamMonitorUpstream node.
	UpstreamMonitorUpstreamUpsertOne struct {
		create *UpstreamMonitorUpstreamCreate
	}

	// UpstreamMonitorUpstreamUpsert is the "OnConflict" setter.
	UpstreamMonitorUpstreamUpsert struct {
		*sql.UpdateSet
	}
)

// SetBaseURL sets the "base_url" field.
func (u *UpstreamMonitorUpstreamUpsert) SetBaseURL(v string) *UpstreamMonitorUpstreamUpsert {
	u.Set(upstreammonitorupstream.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsert) UpdateBaseURL() *UpstreamMonitorUpstreamUpsert {
	u.SetExcluded(upstreammonitorupstream.FieldBaseURL)
	return u
}

// SetName sets the "name" field.
func (u *UpstreamMonitorUpstreamUpsert) SetName(v string) *UpstreamMonitorUpstreamUpsert {
	u.Set(upstreammonitorupstream.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsert) UpdateName() *UpstreamMonitorUpstreamUpsert {
	u.SetExcluded(upstreammonitorupstream.FieldName)
	return u
}

// SetUpstreamType sets the "upstream_type" field.
func (u *UpstreamMonitorUpstreamUpsert) SetUpstreamType(v upstreammonitorupstream.UpstreamType) *UpstreamMonitorUpstreamUpsert {
	u.Set(upstreammonitorupstream.FieldUpstreamType, v)
	return u
}

// UpdateUpstreamType sets the "upstream_type" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsert) UpdateUpstreamType() *UpstreamMonitorUpstreamUpsert {
	u.SetExcluded(upstreammonitorupstream.FieldUpstreamType)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamMonitorUpstreamUpsert) SetEnabled(v bool) *UpstreamMonitorUpstreamUpsert {
	u.Set(upstreammonitorupstream.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsert) UpdateEnabled() *UpstreamMonitorUpstreamUpsert {
	u.SetExcluded(upstreammonitorupstream.FieldEnabled)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamMonitorUpstreamUpsert) SetUpdatedAt(v time.Time) *UpstreamMonitorUpstreamUpsert {
	u.Set(upstreammonitorupstream.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsert) UpdateUpdatedAt() *UpstreamMonitorUpstreamUpsert {
	u.SetExcluded(upstreammonitorupstream.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamMonitorUpstream.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamMonitorUpstreamUpsertOne) UpdateNewValues() *UpstreamMonitorUpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreammonitorupstream.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamMonitorUpstream.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamMonitorUpstreamUpsertOne) Ignore() *UpstreamMonitorUpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamMonitorUpstreamUpsertOne) DoNothing() *UpstreamMonitorUpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamMonitorUpstreamCreate.OnConflict
// documentation for more info.
func (u *UpstreamMonitorUpstreamUpsertOne) Update(set func(*UpstreamMonitorUpstreamUpsert)) *UpstreamMonitorUpstreamUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamMonitorUpstreamUpsert{UpdateSet: update})
	}))
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamMonitorUpstreamUpsertOne) SetBaseURL(v string) *UpstreamMonitorUpstreamUpsertOne {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsertOne) UpdateBaseURL() *UpstreamMonitorUpstreamUpsertOne {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.UpdateBaseURL()
	})
}

// SetName sets the "name" field.
func (u *UpstreamMonitorUpstreamUpsertOne) SetName(v string) *UpstreamMonitorUpstreamUpsertOne {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsertOne) UpdateName() *UpstreamMonitorUpstreamUpsertOne {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.UpdateName()
	})
}

// SetUpstreamType sets the "upstream_type" field.
func (u *UpstreamMonitorUpstreamUpsertOne) SetUpstreamType(v upstreammonitorupstream.UpstreamType) *UpstreamMonitorUpstreamUpsertOne {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.SetUpstreamType(v)
	})
}

// UpdateUpstreamType sets the "upstream_type" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsertOne) UpdateUpstreamType() *UpstreamMonitorUpstreamUpsertOne {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.UpdateUpstreamType()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamMonitorUpstreamUpsertOne) SetEnabled(v bool) *UpstreamMonitorUpstreamUpsertOne {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsertOne) UpdateEnabled() *UpstreamMonitorUpstreamUpsertOne {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamMonitorUpstreamUpsertOne) SetUpdatedAt(v time.Time) *UpstreamMonitorUpstreamUpsertOne {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsertOne) UpdateUpdatedAt() *UpstreamMonitorUpstreamUpsertOne {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UpstreamMonitorUpstreamUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamMonitorUpstreamCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamMonitorUpstreamUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamMonitorUpstreamUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamMonitorUpstreamUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamMonitorUpstreamCreateBulk is the builder for creating many UpstreamMonitorUpstream entities in bulk.
type UpstreamMonitorUpstreamCreateBulk struct {
	config
	err      error
	builders []*UpstreamMonitorUpstreamCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamMonitorUpstream entities in the database.
func (_c *UpstreamMonitorUpstreamCreateBulk) Save(ctx context.Context) ([]*UpstreamMonitorUpstream, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamMonitorUpstream, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamMonitorUpstreamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamMonitorUpstreamCreateBulk) SaveX(ctx context.Context) []*UpstreamMonitorUpstream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamMonitorUpstreamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamMonitorUpstreamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamMonitorUpstream.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamMonitorUpstreamUpsert) {
//			SetBaseURL(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamMonitorUpstreamCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamMonitorUpstreamUpsertBulk {
	_c.conflict = opts
	return &UpstreamMonitorUpstreamUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamMonitorUpstream.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamMonitorUpstreamCreateBulk) OnConflictColumns(columns ...string) *UpstreamMonitorUpstreamUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamMonitorUpstreamUpsertBulk{
		create: _c,
	}
}

// UpstreamMonitorUpstreamUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamMonitorUpstream nodes.
type UpstreamMonitorUpstreamUpsertBulk struct {
	create *UpstreamMonitorUpstreamCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamMonitorUpstream.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamMonitorUpstreamUpsertBulk) UpdateNewValues() *UpstreamMonitorUpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreammonitorupstream.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamMonitorUpstream.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamMonitorUpstreamUpsertBulk) Ignore() *UpstreamMonitorUpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamMonitorUpstreamUpsertBulk) DoNothing() *UpstreamMonitorUpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamMonitorUpstreamCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamMonitorUpstreamUpsertBulk) Update(set func(*UpstreamMonitorUpstreamUpsert)) *UpstreamMonitorUpstreamUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamMonitorUpstreamUpsert{UpdateSet: update})
	}))
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamMonitorUpstreamUpsertBulk) SetBaseURL(v string) *UpstreamMonitorUpstreamUpsertBulk {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsertBulk) UpdateBaseURL() *UpstreamMonitorUpstreamUpsertBulk {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.UpdateBaseURL()
	})
}

// SetName sets the "name" field.
func (u *UpstreamMonitorUpstreamUpsertBulk) SetName(v string) *UpstreamMonitorUpstreamUpsertBulk {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsertBulk) UpdateName() *UpstreamMonitorUpstreamUpsertBulk {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.UpdateName()
	})
}

// SetUpstreamType sets the "upstream_type" field.
func (u *UpstreamMonitorUpstreamUpsertBulk) SetUpstreamType(v upstreammonitorupstream.UpstreamType) *UpstreamMonitorUpstreamUpsertBulk {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.SetUpstreamType(v)
	})
}

// UpdateUpstreamType sets the "upstream_type" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsertBulk) UpdateUpstreamType() *UpstreamMonitorUpstreamUpsertBulk {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.UpdateUpstreamType()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamMonitorUpstreamUpsertBulk) SetEnabled(v bool) *UpstreamMonitorUpstreamUpsertBulk {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsertBulk) UpdateEnabled() *UpstreamMonitorUpstreamUpsertBulk {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamMonitorUpstreamUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamMonitorUpstreamUpsertBulk {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamMonitorUpstreamUpsertBulk) UpdateUpdatedAt() *UpstreamMonitorUpstreamUpsertBulk {
	return u.Update(func(s *UpstreamMonitorUpstreamUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UpstreamMonitorUpstreamUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamMonitorUpstreamCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamMonitorUpstreamCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamMonitorUpstreamUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
