// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamerrorrecord"
)

// UpstreamErrorRecordCreate is the builder for creating a UpstreamErrorRecord entity.
type UpstreamErrorRecordCreate struct {
	config
	mutation *UpstreamErrorRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUpstreamType sets the "upstream_type" field.
func (_c *UpstreamErrorRecordCreate) SetUpstreamType(v string) *UpstreamErrorRecordCreate {
	_c.mutation.SetUpstreamType(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *UpstreamErrorRecordCreate) SetAccountID(v int64) *UpstreamErrorRecordCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetErrorType sets the "error_type" field.
func (_c *UpstreamErrorRecordCreate) SetErrorType(v string) *UpstreamErrorRecordCreate {
	_c.mutation.SetErrorType(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *UpstreamErrorRecordCreate) SetErrorMessage(v string) *UpstreamErrorRecordCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *UpstreamErrorRecordCreate) SetNillableErrorMessage(v *string) *UpstreamErrorRecordCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetHTTPStatus sets the "http_status" field.
func (_c *UpstreamErrorRecordCreate) SetHTTPStatus(v int) *UpstreamErrorRecordCreate {
	_c.mutation.SetHTTPStatus(v)
	return _c
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_c *UpstreamErrorRecordCreate) SetNillableHTTPStatus(v *int) *UpstreamErrorRecordCreate {
	if v != nil {
		_c.SetHTTPStatus(*v)
	}
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *UpstreamErrorRecordCreate) SetOccurredAt(v time.Time) *UpstreamErrorRecordCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// Mutation returns the UpstreamErrorRecordMutation object of the builder.
func (_c *UpstreamErrorRecordCreate) Mutation() *UpstreamErrorRecordMutation {
	return _c.mutation
}

// Save creates the UpstreamErrorRecord in the database.
func (_c *UpstreamErrorRecordCreate) Save(ctx context.Context) (*UpstreamErrorRecord, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamErrorRecordCreate) SaveX(ctx context.Context) *UpstreamErrorRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamErrorRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamErrorRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamErrorRecordCreate) check() error {
	if _, ok := _c.mutation.UpstreamType(); !ok {
		return &ValidationError{Name: "upstream_type", err: errors.New(`ent: missing required field "UpstreamErrorRecord.upstream_type"`)}
	}
	if v, ok := _c.mutation.UpstreamType(); ok {
		if err := upstreamerrorrecord.UpstreamTypeValidator(v); err != nil {
			return &ValidationError{Name: "upstream_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamErrorRecord.upstream_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "UpstreamErrorRecord.account_id"`)}
	}
	if _, ok := _c.mutation.ErrorType(); !ok {
		return &ValidationError{Name: "error_type", err: errors.New(`ent: missing required field "UpstreamErrorRecord.error_type"`)}
	}
	if v, ok := _c.mutation.ErrorType(); ok {
		if err := upstreamerrorrecord.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamErrorRecord.error_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "UpstreamErrorRecord.occurred_at"`)}
	}
	return nil
}

func (_c *UpstreamErrorRecordCreate) sqlSave(ctx context.Context) (*UpstreamErrorRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamErrorRecordCreate) createSpec() (*UpstreamErrorRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamErrorRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamerrorrecord.Table, sqlgraph.NewFieldSpec(upstreamerrorrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UpstreamType(); ok {
		_spec.SetField(upstreamerrorrecord.FieldUpstreamType, field.TypeString, value)
		_node.UpstreamType = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(upstreamerrorrecord.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.ErrorType(); ok {
		_spec.SetField(upstreamerrorrecord.FieldErrorType, field.TypeString, value)
		_node.ErrorType = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(upstreamerrorrecord.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.HTTPStatus(); ok {
		_spec.SetField(upstreamerrorrecord.FieldHTTPStatus, field.TypeInt, value)
		_node.HTTPStatus = &value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(upstreamerrorrecord.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamErrorRecord.Create().
//		SetUpstreamType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamErrorRecordUpsert) {
//			SetUpstreamType(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamErrorRecordCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamErrorRecordUpsertOne {
	_c.conflict = opts
	return &UpstreamErrorRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamErrorRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamErrorRecordCreate) OnConflictColumns(columns ...string) *UpstreamErrorRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamErrorRecordUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamErrorRecordUpsertOne is the builder for "upsert"-ing
	//  one UpstreamErrorRecord node.
	UpstreamErrorRecordUpsertOne struct {
		create *UpstreamErrorRecordCreate
	}

	// UpstreamErrorRecordUpsert is the "OnConflict" setter.
	UpstreamErrorRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpstreamType sets the "upstream_type" field.
func (u *UpstreamErrorRecordUpsert) SetUpstreamType(v string) *UpstreamErrorRecordUpsert {
	u.Set(upstreamerrorrecord.FieldUpstreamType, v)
	return u
}

// UpdateUpstreamType sets the "upstream_type" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsert) UpdateUpstreamType() *UpstreamErrorRecordUpsert {
	u.SetExcluded(upstreamerrorrecord.FieldUpstreamType)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *UpstreamErrorRecordUpsert) SetAccountID(v int64) *UpstreamErrorRecordUpsert {
	u.Set(upstreamerrorrecord.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsert) UpdateAccountID() *UpstreamErrorRecordUpsert {
	u.SetExcluded(upstreamerrorrecord.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *UpstreamErrorRecordUpsert) AddAccountID(v int64) *UpstreamErrorRecordUpsert {
	u.Add(upstreamerrorrecord.FieldAccountID, v)
	return u
}

// SetErrorType sets the "error_type" field.
func (u *UpstreamErrorRecordUpsert) SetErrorType(v string) *UpstreamErrorRecordUpsert {
	u.Set(upstreamerrorrecord.FieldErrorType, v)
	return u
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsert) UpdateErrorType() *UpstreamErrorRecordUpsert {
	u.SetExcluded(upstreamerrorrecord.FieldErrorType)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *UpstreamErrorRecordUpsert) SetErrorMessage(v string) *UpstreamErrorRecordUpsert {
	u.Set(upstreamerrorrecord.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsert) UpdateErrorMessage() *UpstreamErrorRecordUpsert {
	u.SetExcluded(upstreamerrorrecord.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *UpstreamErrorRecordUpsert) ClearErrorMessage() *UpstreamErrorRecordUpsert {
	u.SetNull(upstreamerrorrecord.FieldErrorMessage)
	return u
}

// SetHTTPStatus sets the "http_status" field.
func (u *UpstreamErrorRecordUpsert) SetHTTPStatus(v int) *UpstreamErrorRecordUpsert {
	u.Set(upstreamerrorrecord.FieldHTTPStatus, v)
	return u
}

// UpdateHTTPStatus sets the "http_status" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsert) UpdateHTTPStatus() *UpstreamErrorRecordUpsert {
	u.SetExcluded(upstreamerrorrecord.FieldHTTPStatus)
	return u
}

// AddHTTPStatus adds v to the "http_status" field.
func (u *UpstreamErrorRecordUpsert) AddHTTPStatus(v int) *UpstreamErrorRecordUpsert {
	u.Add(upstreamerrorrecord.FieldHTTPStatus, v)
	return u
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (u *UpstreamErrorRecordUpsert) ClearHTTPStatus() *UpstreamErrorRecordUpsert {
	u.SetNull(upstreamerrorrecord.FieldHTTPStatus)
	return u
}

// SetOccurredAt sets the "occurred_at" field.
func (u *UpstreamErrorRecordUpsert) SetOccurredAt(v time.Time) *UpstreamErrorRecordUpsert {
	u.Set(upstreamerrorrecord.FieldOccurredAt, v)
	return u
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsert) UpdateOccurredAt() *UpstreamErrorRecordUpsert {
	u.SetExcluded(upstreamerrorrecord.FieldOccurredAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamErrorRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamErrorRecordUpsertOne) UpdateNewValues() *UpstreamErrorRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamErrorRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamErrorRecordUpsertOne) Ignore() *UpstreamErrorRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamErrorRecordUpsertOne) DoNothing() *UpstreamErrorRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamErrorRecordCreate.OnConflict
// documentation for more info.
func (u *UpstreamErrorRecordUpsertOne) Update(set func(*UpstreamErrorRecordUpsert)) *UpstreamErrorRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamErrorRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpstreamType sets the "upstream_type" field.
func (u *UpstreamErrorRecordUpsertOne) SetUpstreamType(v string) *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetUpstreamType(v)
	})
}

// UpdateUpstreamType sets the "upstream_type" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertOne) UpdateUpstreamType() *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateUpstreamType()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UpstreamErrorRecordUpsertOne) SetAccountID(v int64) *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UpstreamErrorRecordUpsertOne) AddAccountID(v int64) *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertOne) UpdateAccountID() *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateAccountID()
	})
}

// SetErrorType sets the "error_type" field.
func (u *UpstreamErrorRecordUpsertOne) SetErrorType(v string) *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetErrorType(v)
	})
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertOne) UpdateErrorType() *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateErrorType()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *UpstreamErrorRecordUpsertOne) SetErrorMessage(v string) *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertOne) UpdateErrorMessage() *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *UpstreamErrorRecordUpsertOne) ClearErrorMessage() *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.ClearErrorMessage()
	})
}

// SetHTTPStatus sets the "http_status" field.
func (u *UpstreamErrorRecordUpsertOne) SetHTTPStatus(v int) *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetHTTPStatus(v)
	})
}

// AddHTTPStatus adds v to the "http_status" field.
func (u *UpstreamErrorRecordUpsertOne) AddHTTPStatus(v int) *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.AddHTTPStatus(v)
	})
}

// UpdateHTTPStatus sets the "http_status" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertOne) UpdateHTTPStatus() *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateHTTPStatus()
	})
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (u *UpstreamErrorRecordUpsertOne) ClearHTTPStatus() *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.ClearHTTPStatus()
	})
}

// SetOccurredAt sets the "occurred_at" field.
func (u *UpstreamErrorRecordUpsertOne) SetOccurredAt(v time.Time) *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetOccurredAt(v)
	})
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertOne) UpdateOccurredAt() *UpstreamErrorRecordUpsertOne {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateOccurredAt()
	})
}

// Exec executes the query.
func (u *UpstreamErrorRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamErrorRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamErrorRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamErrorRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamErrorRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamErrorRecordCreateBulk is the builder for creating many UpstreamErrorRecord entities in bulk.
type UpstreamErrorRecordCreateBulk struct {
	config
	err      error
	builders []*UpstreamErrorRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamErrorRecord entities in the database.
func (_c *UpstreamErrorRecordCreateBulk) Save(ctx context.Context) ([]*UpstreamErrorRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamErrorRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamErrorRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamErrorRecordCreateBulk) SaveX(ctx context.Context) []*UpstreamErrorRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamErrorRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamErrorRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamErrorRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamErrorRecordUpsert) {
//			SetUpstreamType(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamErrorRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamErrorRecordUpsertBulk {
	_c.conflict = opts
	return &UpstreamErrorRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamErrorRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamErrorRecordCreateBulk) OnConflictColumns(columns ...string) *UpstreamErrorRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamErrorRecordUpsertBulk{
		create: _c,
	}
}

// UpstreamErrorRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamErrorRecord nodes.
type UpstreamErrorRecordUpsertBulk struct {
	create *UpstreamErrorRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamErrorRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamErrorRecordUpsertBulk) UpdateNewValues() *UpstreamErrorRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamErrorRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamErrorRecordUpsertBulk) Ignore() *UpstreamErrorRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamErrorRecordUpsertBulk) DoNothing() *UpstreamErrorRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamErrorRecordCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamErrorRecordUpsertBulk) Update(set func(*UpstreamErrorRecordUpsert)) *UpstreamErrorRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamErrorRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpstreamType sets the "upstream_type" field.
func (u *UpstreamErrorRecordUpsertBulk) SetUpstreamType(v string) *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetUpstreamType(v)
	})
}

// UpdateUpstreamType sets the "upstream_type" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertBulk) UpdateUpstreamType() *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateUpstreamType()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UpstreamErrorRecordUpsertBulk) SetAccountID(v int64) *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UpstreamErrorRecordUpsertBulk) AddAccountID(v int64) *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertBulk) UpdateAccountID() *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateAccountID()
	})
}

// SetErrorType sets the "error_type" field.
func (u *UpstreamErrorRecordUpsertBulk) SetErrorType(v string) *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetErrorType(v)
	})
}

// UpdateErrorType sets the "error_type" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertBulk) UpdateErrorType() *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateErrorType()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *UpstreamErrorRecordUpsertBulk) SetErrorMessage(v string) *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertBulk) UpdateErrorMessage() *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *UpstreamErrorRecordUpsertBulk) ClearErrorMessage() *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.ClearErrorMessage()
	})
}

// SetHTTPStatus sets the "http_status" field.
func (u *UpstreamErrorRecordUpsertBulk) SetHTTPStatus(v int) *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetHTTPStatus(v)
	})
}

// AddHTTPStatus adds v to the "http_status" field.
func (u *UpstreamErrorRecordUpsertBulk) AddHTTPStatus(v int) *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.AddHTTPStatus(v)
	})
}

// UpdateHTTPStatus sets the "http_status" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertBulk) UpdateHTTPStatus() *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateHTTPStatus()
	})
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (u *UpstreamErrorRecordUpsertBulk) ClearHTTPStatus() *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.ClearHTTPStatus()
	})
}

// SetOccurredAt sets the "occurred_at" field.
func (u *UpstreamErrorRecordUpsertBulk) SetOccurredAt(v time.Time) *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.SetOccurredAt(v)
	})
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *UpstreamErrorRecordUpsertBulk) UpdateOccurredAt() *UpstreamErrorRecordUpsertBulk {
	return u.Update(func(s *UpstreamErrorRecordUpsert) {
		s.UpdateOccurredAt()
	})
}

// Exec executes the query.
func (u *UpstreamErrorRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamErrorRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamErrorRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamErrorRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
