// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamerrorrecord"
)

// UpstreamErrorRecordUpdate is the builder for updating UpstreamErrorRecord entities.
type UpstreamErrorRecordUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamErrorRecordMutation
}

// Where appends a list predicates to the UpstreamErrorRecordUpdate builder.
func (_u *UpstreamErrorRecordUpdate) Where(ps ...predicate.UpstreamErrorRecord) *UpstreamErrorRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpstreamType sets the "upstream_type" field.
func (_u *UpstreamErrorRecordUpdate) SetUpstreamType(v string) *UpstreamErrorRecordUpdate {
	_u.mutation.SetUpstreamType(v)
	return _u
}

// SetNillableUpstreamType sets the "upstream_type" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdate) SetNillableUpstreamType(v *string) *UpstreamErrorRecordUpdate {
	if v != nil {
		_u.SetUpstreamType(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UpstreamErrorRecordUpdate) SetAccountID(v int64) *UpstreamErrorRecordUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdate) SetNillableAccountID(v *int64) *UpstreamErrorRecordUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UpstreamErrorRecordUpdate) AddAccountID(v int64) *UpstreamErrorRecordUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetErrorType sets the "error_type" field.
func (_u *UpstreamErrorRecordUpdate) SetErrorType(v string) *UpstreamErrorRecordUpdate {
	_u.mutation.SetErrorType(v)
	return _u
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdate) SetNillableErrorType(v *string) *UpstreamErrorRecordUpdate {
	if v != nil {
		_u.SetErrorType(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *UpstreamErrorRecordUpdate) SetErrorMessage(v string) *UpstreamErrorRecordUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdate) SetNillableErrorMessage(v *string) *UpstreamErrorRecordUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *UpstreamErrorRecordUpdate) ClearErrorMessage() *UpstreamErrorRecordUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetHTTPStatus sets the "http_status" field.
func (_u *UpstreamErrorRecordUpdate) SetHTTPStatus(v int) *UpstreamErrorRecordUpdate {
	_u.mutation.ResetHTTPStatus()
	_u.mutation.SetHTTPStatus(v)
	return _u
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdate) SetNillableHTTPStatus(v *int) *UpstreamErrorRecordUpdate {
	if v != nil {
		_u.SetHTTPStatus(*v)
	}
	return _u
}

// AddHTTPStatus adds value to the "http_status" field.
func (_u *UpstreamErrorRecordUpdate) AddHTTPStatus(v int) *UpstreamErrorRecordUpdate {
	_u.mutation.AddHTTPStatus(v)
	return _u
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (_u *UpstreamErrorRecordUpdate) ClearHTTPStatus() *UpstreamErrorRecordUpdate {
	_u.mutation.ClearHTTPStatus()
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *UpstreamErrorRecordUpdate) SetOccurredAt(v time.Time) *UpstreamErrorRecordUpdate {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdate) SetNillableOccurredAt(v *time.Time) *UpstreamErrorRecordUpdate {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// Mutation returns the UpstreamErrorRecordMutation object of the builder.
func (_u *UpstreamErrorRecordUpdate) Mutation() *UpstreamErrorRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamErrorRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamErrorRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamErrorRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamErrorRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamErrorRecordUpdate) check() error {
	if v, ok := _u.mutation.UpstreamType(); ok {
		if err := upstreamerrorrecord.UpstreamTypeValidator(v); err != nil {
			return &ValidationError{Name: "upstream_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamErrorRecord.upstream_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorType(); ok {
		if err := upstreamerrorrecord.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamErrorRecord.error_type": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamErrorRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamerrorrecord.Table, upstreamerrorrecord.Columns, sqlgraph.NewFieldSpec(upstreamerrorrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpstreamType(); ok {
		_spec.SetField(upstreamerrorrecord.FieldUpstreamType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(upstreamerrorrecord.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(upstreamerrorrecord.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorType(); ok {
		_spec.SetField(upstreamerrorrecord.FieldErrorType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(upstreamerrorrecord.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(upstreamerrorrecord.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.HTTPStatus(); ok {
		_spec.SetField(upstreamerrorrecord.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(upstreamerrorrecord.FieldHTTPStatus, field.TypeInt, value)
	}
	if _u.mutation.HTTPStatusCleared() {
		_spec.ClearField(upstreamerrorrecord.FieldHTTPStatus, field.TypeInt)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(upstreamerrorrecord.FieldOccurredAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamerrorrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamErrorRecordUpdateOne is the builder for updating a single UpstreamErrorRecord entity.
type UpstreamErrorRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamErrorRecordMutation
}

// SetUpstreamType sets the "upstream_type" field.
func (_u *UpstreamErrorRecordUpdateOne) SetUpstreamType(v string) *UpstreamErrorRecordUpdateOne {
	_u.mutation.SetUpstreamType(v)
	return _u
}

// SetNillableUpstreamType sets the "upstream_type" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdateOne) SetNillableUpstreamType(v *string) *UpstreamErrorRecordUpdateOne {
	if v != nil {
		_u.SetUpstreamType(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UpstreamErrorRecordUpdateOne) SetAccountID(v int64) *UpstreamErrorRecordUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdateOne) SetNillableAccountID(v *int64) *UpstreamErrorRecordUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UpstreamErrorRecordUpdateOne) AddAccountID(v int64) *UpstreamErrorRecordUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetErrorType sets the "error_type" field.
func (_u *UpstreamErrorRecordUpdateOne) SetErrorType(v string) *UpstreamErrorRecordUpdateOne {
	_u.mutation.SetErrorType(v)
	return _u
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdateOne) SetNillableErrorType(v *string) *UpstreamErrorRecordUpdateOne {
	if v != nil {
		_u.SetErrorType(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *UpstreamErrorRecordUpdateOne) SetErrorMessage(v string) *UpstreamErrorRecordUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdateOne) SetNillableErrorMessage(v *string) *UpstreamErrorRecordUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *UpstreamErrorRecordUpdateOne) ClearErrorMessage() *UpstreamErrorRecordUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetHTTPStatus sets the "http_status" field.
func (_u *UpstreamErrorRecordUpdateOne) SetHTTPStatus(v int) *UpstreamErrorRecordUpdateOne {
	_u.mutation.ResetHTTPStatus()
	_u.mutation.SetHTTPStatus(v)
	return _u
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdateOne) SetNillableHTTPStatus(v *int) *UpstreamErrorRecordUpdateOne {
	if v != nil {
		_u.SetHTTPStatus(*v)
	}
	return _u
}

// AddHTTPStatus adds value to the "http_status" field.
func (_u *UpstreamErrorRecordUpdateOne) AddHTTPStatus(v int) *UpstreamErrorRecordUpdateOne {
	_u.mutation.AddHTTPStatus(v)
	return _u
}

// ClearHTTPStatus clears the value of the "http_status" field.
func (_u *UpstreamErrorRecordUpdateOne) ClearHTTPStatus() *UpstreamErrorRecordUpdateOne {
	_u.mutation.ClearHTTPStatus()
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *UpstreamErrorRecordUpdateOne) SetOccurredAt(v time.Time) *UpstreamErrorRecordUpdateOne {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *UpstreamErrorRecordUpdateOne) SetNillableOccurredAt(v *time.Time) *UpstreamErrorRecordUpdateOne {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// Mutation returns the UpstreamErrorRecordMutation object of the builder.
func (_u *UpstreamErrorRecordUpdateOne) Mutation() *UpstreamErrorRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamErrorRecordUpdate builder.
func (_u *UpstreamErrorRecordUpdateOne) Where(ps ...predicate.UpstreamErrorRecord) *UpstreamErrorRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamErrorRecordUpdateOne) Select(field string, fields ...string) *UpstreamErrorRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamErrorRecord entity.
func (_u *UpstreamErrorRecordUpdateOne) Save(ctx context.Context) (*UpstreamErrorRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamErrorRecordUpdateOne) SaveX(ctx context.Context) *UpstreamErrorRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamErrorRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamErrorRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamErrorRecordUpdateOne) check() error {
	if v, ok := _u.mutation.UpstreamType(); ok {
		if err := upstreamerrorrecord.UpstreamTypeValidator(v); err != nil {
			return &ValidationError{Name: "upstream_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamErrorRecord.upstream_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorType(); ok {
		if err := upstreamerrorrecord.ErrorTypeValidator(v); err != nil {
			return &ValidationError{Name: "error_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamErrorRecord.error_type": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamErrorRecordUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamErrorRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamerrorrecord.Table, upstreamerrorrecord.Columns, sqlgraph.NewFieldSpec(upstreamerrorrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamErrorRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamerrorrecord.FieldID)
		for _, f := range fields {
			if !upstreamerrorrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamerrorrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpstreamType(); ok {
		_spec.SetField(upstreamerrorrecord.FieldUpstreamType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(upstreamerrorrecord.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(upstreamerrorrecord.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ErrorType(); ok {
		_spec.SetField(upstreamerrorrecord.FieldErrorType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(upstreamerrorrecord.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(upstreamerrorrecord.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.HTTPStatus(); ok {
		_spec.SetField(upstreamerrorrecord.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(upstreamerrorrecord.FieldHTTPStatus, field.TypeInt, value)
	}
	if _u.mutation.HTTPStatusCleared() {
		_spec.ClearField(upstreamerrorrecord.FieldHTTPStatus, field.TypeInt)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(upstreamerrorrecord.FieldOccurredAt, field.TypeTime, value)
	}
	_node = &UpstreamErrorRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamerrorrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
