import {validateConfig} from '/homepage-assets/contract.mjs';
const $=s=>document.querySelector(s);
let state,config,dirty=false,active='brand',source='fixture',busy=false;
const titles={brand:'品牌与首屏',navigation:'导航与按钮',api:'API 接入地址',models:'模型目录',capabilities:'能力卡片',announcement:'公告配置',footer:'页脚链接',versions:'版本与发布',json:'导入与 JSON'};
function el(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function feedback(t,error=false){$('#feedback').hidden=false;$('#feedback').textContent=t;$('#feedback').classList.toggle('error',error);}
async function api(p,body,method='POST'){const r=await fetch('/admin-api/'+p,{method:body===undefined?'GET':method,headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(v.error?.message||'操作失败');return v;}
function update(){ $('#dirty-state').textContent=dirty?'有未保存修改 · 请先保存再发布':`草稿 #${state.draft_revision} · 已保存`;$('#publish-status').textContent='已发布 r'+state.published.revision;$('#publish').disabled=dirty||busy;for(const id of ['save','export','preview'])$('#'+id).disabled=busy;}
function changed(){dirty=true;update();}
function adopt(s){state=s;config=structuredClone(s.draft);dirty=false;update();render();}
function card(title,description){const e=el('article','card');e.append(el('h2','',title),el('p','',description));$('#editor').append(e);return e;}
function field(parent,obj,key,label,type='text',options=[]){const l=el('label','field'+(type==='textarea'?' full':''));l.append(el('span','',label));const input=el(type==='textarea'?'textarea':type==='select'?'select':'input');
  if(type==='select')for(const [value,text]of options){const o=el('option','',text);o.value=value;input.append(o);}else if(type!=='textarea')input.type=type;
  if(type==='checkbox')input.checked=obj[key];else input.value=obj[key]??'';
  input.oninput=()=>{obj[key]=type==='checkbox'?input.checked:type==='number'?Number(input.value):input.value;changed();};l.append(input);parent.append(l);return input;
}
function fields(c){const div=el('div','fields');c.append(div);return div;}
function button(text,fn){const b=el('button','btn',text);b.type='button';b.onclick=fn;return b;}
const variants=[['primary','主要按钮'],['secondary','次要按钮'],['text','文本链接']];
function actions(c,arr){editList(c,arr,()=>({id:crypto.randomUUID(),label:'新入口',href:'/login',enabled:true,variant:'secondary'}),(p,x)=>{field(p,x,'label','按钮文案');field(p,x,'href','跳转地址（支持 /login、HTTPS 外链或 http://qm.qq.com/... QQ 群链接）');field(p,x,'variant','样式','select',variants);field(p,x,'enabled','启用','checkbox');});}
function editList(c,arr,make,draw){arr.forEach((x,i)=>{const row=el('div','list-row'),top=el('div','list-top'),controls=el('div','row-buttons');top.append(el('span','',`#${i+1} · ${x.id}`));
    for(const [label,delta]of [['↑',-1],['↓',1]]){const b=button(label,()=>{const target=i+delta;if(target>=0&&target<arr.length){[arr[i],arr[target]]=[arr[target],arr[i]];changed();render();}});b.setAttribute('aria-label',`第 ${i+1} 项${delta<0?'上移':'下移'}`);controls.append(b);}
    controls.append(button('移除',()=>{arr.splice(i,1);changed();render();}));top.append(controls);row.append(top);draw(fields(row),x);c.append(row);});c.append(button('＋ 添加一项',()=>{arr.push(make());changed();render();}));}
function render(){ $('#section-title').textContent=titles[active];$('#sections').replaceChildren(...Object.entries(titles).map(([id,title])=>{const b=button(title,()=>{active=id;render();});b.className=id===active?'active':'';return b;}));$('#editor').replaceChildren();
  if(active==='brand'){const p=fields(card('品牌与首屏','控制品牌、首屏标题和介绍文案。Logo 图片仅支持随静态包部署的 /homepage-assets/ 文件。'));field(p,config.brand,'name','品牌名称');field(p,config.brand,'logo_text','Logo 文字');field(p,config.brand,'logo_url','Logo 本地图片地址');for(const [key,title]of [['badge','顶部徽标'],['title','标题第一行'],['accent','强调标题'],['description','介绍文案']])field(p,config.hero,key,title,key==='description'?'textarea':'text');}
  if(active==='navigation'){actions(card('顶部导航','可增删、排序、停用，地址仅支持站内安全路径、锚点和 HTTPS 外链。'),config.navigation);actions(card('首屏按钮','登录入口建议 /login，注册 /register，控制台 /dashboard。'),config.actions);}
  if(active==='api'){const p=fields(card('接口地址','该地址用于展示和复制，不会改变 Sub2API 实际网关配置。'));field(p,config.api,'enabled','展示地址卡片','checkbox');field(p,config.api,'base_url','API Base URL');field(p,config.api,'label','卡片标题');field(p,config.api,'hint','地址说明','textarea');field(p,config.api,'copy_enabled','允许复制','checkbox');field(p,config.runtime,'system_settings','读取同源系统公开设置（名称、地址、注册开关）','checkbox');}
  if(active==='models'){const c=card('模型目录','下面是首页展示项。公开候选导入仅去重模型名称，分类需要管理员确认；不会读取账号凭据或修改授权。');const p=fields(c);field(p,config.models,'enabled','展示模型区','checkbox');field(p,config.models,'title','区域标题');field(p,config.models,'description','目录说明','textarea');
    c.append(button('载入公开模型候选',async()=>{try{const v=await api('candidates');const list=el('div','candidate-list'),selected=new Map(config.models.items.map(m=>[m.id,m]));for(const m of v.data){const l=el('label'),check=el('input');check.type='checkbox';check.checked=selected.has(m.id);check.onchange=()=>{if(check.checked)selected.set(m.id,m);else selected.delete(m.id);};l.append(check,document.createTextNode(' '+m.id));list.append(l);}c.append(list,button('应用候选选择',()=>{config.models.items=[...selected.values()];config.models.observed_at=v.observed_at;changed();render();}));feedback(`已载入 ${v.data.length} 个候选，来源：${v.source==='live'?'生产匿名公开接口':'本地联调示例'}。`);}catch(e){feedback(e.message,true);}}));
    editList(card('展示项','条目顺序就是首页排序，已停用的条目不进入公开快照。'),config.models.items,()=>({id:'model-'+crypto.randomUUID().slice(0,8),label:'新模型',category:'text',enabled:true}),(p,x)=>{field(p,x,'id','模型 ID');field(p,x,'label','展示名称');field(p,x,'category','能力分类','select',[['text','文本'],['code','代码'],['image','图像'],['video','视频']]);field(p,x,'enabled','启用','checkbox');});}
  if(active==='capabilities')editList(card('能力卡片','配置首页能力说明。'),config.capabilities,()=>({id:crypto.randomUUID(),icon:'layers',title:'新能力',description:'',enabled:true}),(p,x)=>{field(p,x,'title','标题');field(p,x,'icon','图标','select',[['layers','统一入口'],['key','密钥'],['shield','安全'],['bolt','快速'],['globe','网络'],['chart','用量']]);field(p,x,'description','说明','textarea');field(p,x,'enabled','启用','checkbox');});
  if(active==='announcement'){const n=config.announcement,p=fields(card('首页公开公告','独立的首页公告。不会自动公开 Sub2API 用户定向公告。修改正文后请增加公告版本，使浏览器重新提示。'));field(p,n,'enabled','启用公告','checkbox');field(p,n,'id','公告 ID');field(p,n,'version','公告版本','number');field(p,n,'title','公告标题');field(p,n,'date','展示日期');field(p,n,'body','正文（纯文本）','textarea');field(p,n,'mode','展示方式','select',[['popup','弹窗 + 公告区'],['banner','横幅'],['silent','仅公告区']]);field(p,n,'policy','自动提示策略','select',[['daily','每天一次'],['once','一次'],['visit','每次访问']]);
    for(const [k,label]of [['starts_at','生效时间（ISO，空表示立即）'],['ends_at','结束时间（ISO，空表示不限制）']]){const input=field(p,n,k,label);input.oninput=()=>{n[k]=input.value||null;changed();};}actions(card('公告按钮','公告内的快捷入口。'),n.actions);}
  if(active==='footer'){field(fields(card('版权','页面底部显示文案。')),config.footer,'copyright','版权文案');actions(card('页脚链接','仅配置已存在的协议、文档或服务地址。'),config.footer.links);}
  if(active==='versions'){const c=card('版本记录','恢复历史只生成草稿。保存后点击发布才影响首页；导出静态包后仍需部署才能影响线上。');for(const v of [state.published,...state.history]){const row=el('div','history'),info=el('div','',`版本 r${v.revision}${v.revision===state.published.revision?' · 当前已发布':''}`);info.append(el('small','',new Date(v.published_at).toLocaleString('zh-CN')));row.append(info,button('恢复为草稿',()=>task(async()=>{const result=await api('restore',{revision:v.revision,expected_revision:state.draft_revision});adopt(result.data);feedback('历史版本已恢复为草稿。请确认后发布。');})));c.append(row);}}
  if(active==='json'){const c=card('导入与导出配置','导入只更改编辑表单，不会自动保存或发布。JSON 由前后端同一套校验器校验。'),ta=el('textarea','json-input');ta.setAttribute('aria-label','完整配置 JSON');ta.value=JSON.stringify(config,null,2);c.append(ta);const row=el('div','inline-actions');row.append(button('应用 JSON',()=>{try{config=validateConfig(JSON.parse(ta.value));changed();render();feedback('JSON 已应用到表单，请保存草稿。');}catch(e){feedback(e.message,true);}}),button('下载当前配置',()=>download({schema_version:1,config},'homepage-draft.json')));const input=el('input');input.type='file';input.accept='.json';input.setAttribute('aria-label','导入配置文件');input.onchange=async()=>{try{const f=input.files[0];if(!f)return;if(f.size>260000)throw new Error('文件过大');const v=JSON.parse(await f.text());config=validateConfig(v.config||v);changed();render();feedback('文件已载入表单，请保存草稿。');}catch(e){feedback(e.message,true);}};row.append(input);c.append(row);}
}
async function task(fn){busy=true;update();try{await fn();}catch(e){feedback(e.message,true);}finally{busy=false;update();}}
function download(v,name){const url=URL.createObjectURL(new Blob([JSON.stringify(v,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#save').onclick=()=>task(async()=>{validateConfig(config);const result=await api('draft',{expected_revision:state.draft_revision,config},'PUT');adopt(result.data);feedback('草稿已写入本机文件。已发布首页保持原版本。');});
$('#publish').onclick=()=>task(async()=>{const result=await api('publish',{expected_revision:state.draft_revision});adopt(result.data);feedback(`本地首页已切换到 r${state.published.revision}。点击“查看已发布首页”验证效果。`);});
$('#export').onclick=()=>task(async()=>{const v=await api('export',{});feedback(`已导出发布版本 r${v.data.revision}：\n${v.data.path}\n静态包只含访客页面和公开配置，可交给 Caddy 部署。`);download({schema_version:1,...state.published},'homepage.public.json');});
$('#preview').onclick=()=>{try{validateConfig(config);const id=crypto.randomUUID(),channel=new BroadcastChannel('relay-preview-'+id);const snapshot=structuredClone(config);channel.onmessage=e=>{if(e.data==='ready'){channel.postMessage(snapshot);channel.close();}};const w=window.open('/?preview='+id,'_blank');if(!w){channel.close();throw new Error('请允许本机页面弹出预览窗口');}setTimeout(()=>channel.close(),12000);}catch(e){feedback(e.message,true);}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
try{const v=await api('state');source=v.source;adopt(v.data);feedback(`配置来源：本机文件。模型联调源：${source==='live'?'生产匿名公开接口（只读）':'本地示例'}。`);}catch(e){feedback(e.message,true);for(const id of ['save','publish','export','preview'])$('#'+id).disabled=true;}
