// Code generated by ent, DO NOT EDIT.

package upstreammonitorupstream

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upstreammonitorupstream type in the database.
	Label = "upstream_monitor_upstream"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldUpstreamType holds the string denoting the upstream_type field in the database.
	FieldUpstreamType = "upstream_type"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the upstreammonitorupstream in the database.
	Table = "upstream_monitor_upstreams"
)

// Columns holds all SQL columns for upstreammonitorupstream fields.
var Columns = []string{
	FieldID,
	FieldBaseURL,
	FieldName,
	FieldUpstreamType,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// UpstreamType defines the type for the "upstream_type" enum field.
type UpstreamType string

// UpstreamType values.
const (
	UpstreamTypeSub2api UpstreamType = "sub2api"
	UpstreamTypeNexapi  UpstreamType = "nexapi"
)

func (ut UpstreamType) String() string {
	return string(ut)
}

// UpstreamTypeValidator is a validator for the "upstream_type" field enum values. It is called by the builders before save.
func UpstreamTypeValidator(ut UpstreamType) error {
	switch ut {
	case UpstreamTypeSub2api, UpstreamTypeNexapi:
		return nil
	default:
		return fmt.Errorf("upstreammonitorupstream: invalid enum value for upstream_type field: %q", ut)
	}
}

// OrderOption defines the ordering options for the UpstreamMonitorUpstream queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByUpstreamType orders the results by the upstream_type field.
func ByUpstreamType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamType, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
