// Code generated by ent, DO NOT EDIT.

package upstreammonitorupstream

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLTE(FieldID, id))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldBaseURL, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldName, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldAccessToken, v))
}

// QuotaDivider applies equality check predicate on the "quota_divider" field. It's identical to QuotaDividerEQ.
func QuotaDivider(v float64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldQuotaDivider, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldUpdatedAt, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldContainsFold(FieldBaseURL, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldContainsFold(FieldName, v))
}

// UpstreamTypeEQ applies the EQ predicate on the "upstream_type" field.
func UpstreamTypeEQ(v UpstreamType) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldUpstreamType, v))
}

// UpstreamTypeNEQ applies the NEQ predicate on the "upstream_type" field.
func UpstreamTypeNEQ(v UpstreamType) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNEQ(FieldUpstreamType, v))
}

// UpstreamTypeIn applies the In predicate on the "upstream_type" field.
func UpstreamTypeIn(vs ...UpstreamType) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldIn(FieldUpstreamType, vs...))
}

// UpstreamTypeNotIn applies the NotIn predicate on the "upstream_type" field.
func UpstreamTypeNotIn(vs ...UpstreamType) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNotIn(FieldUpstreamType, vs...))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenIsNil applies the IsNil predicate on the "access_token" field.
func AccessTokenIsNil() predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldIsNull(FieldAccessToken))
}

// AccessTokenNotNil applies the NotNil predicate on the "access_token" field.
func AccessTokenNotNil() predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNotNull(FieldAccessToken))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldContainsFold(FieldAccessToken, v))
}

// QuotaDividerEQ applies the EQ predicate on the "quota_divider" field.
func QuotaDividerEQ(v float64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldQuotaDivider, v))
}

// QuotaDividerNEQ applies the NEQ predicate on the "quota_divider" field.
func QuotaDividerNEQ(v float64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNEQ(FieldQuotaDivider, v))
}

// QuotaDividerIn applies the In predicate on the "quota_divider" field.
func QuotaDividerIn(vs ...float64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldIn(FieldQuotaDivider, vs...))
}

// QuotaDividerNotIn applies the NotIn predicate on the "quota_divider" field.
func QuotaDividerNotIn(vs ...float64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNotIn(FieldQuotaDivider, vs...))
}

// QuotaDividerGT applies the GT predicate on the "quota_divider" field.
func QuotaDividerGT(v float64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGT(FieldQuotaDivider, v))
}

// QuotaDividerGTE applies the GTE predicate on the "quota_divider" field.
func QuotaDividerGTE(v float64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGTE(FieldQuotaDivider, v))
}

// QuotaDividerLT applies the LT predicate on the "quota_divider" field.
func QuotaDividerLT(v float64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLT(FieldQuotaDivider, v))
}

// QuotaDividerLTE applies the LTE predicate on the "quota_divider" field.
func QuotaDividerLTE(v float64) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLTE(FieldQuotaDivider, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamMonitorUpstream) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamMonitorUpstream) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamMonitorUpstream) predicate.UpstreamMonitorUpstream {
	return predicate.UpstreamMonitorUpstream(sql.NotPredicates(p))
}
